<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graph_sd" nsURI="D:/Eugene_Y/BIT/metagraph/workspace/SAP_LGS/语言/特种飞行器起落架系统总体设计/图元模型/graph_sd.karma" nsPrefix="graph_sd">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram"/>
    <eSuperTypes href="/SAP_LGS/语言/特种飞行器起落架系统总体设计/图元模型/graph_sd.ecore#//Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KLayout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KMatrix"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPlugin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//ValueSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bodies" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="langues" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//AbstractConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceRole">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceMessage">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind">
      <eType xsi:type="ecore:EEnum" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//MessageKind"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangeContext" eType="//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendingEnd" eType="//MessageEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivingEnd" eType="//MessageEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="AsyncMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="SyncMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReplyMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="DestructMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFragment" abstract="true">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coveredInstanceRoles" lowerBound="1" upperBound="-1" eType="//InstanceRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionState" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//StateFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentEnd" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//AbstractFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedInteractionFragments" upperBound="-1" eType="//InteractionFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEnd" abstract="true" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageEnd" eSuperTypes="//AbstractEnd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//SequenceMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEnd" eSuperTypes="//AbstractEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//Execution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gate" eSuperTypes="//MessageEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeLapse" abstract="true">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" ordered="false" lowerBound="1" eType="//InteractionFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finish" ordered="false" lowerBound="1" eType="//InteractionFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFragment" abstract="true" eSuperTypes="//TimeLapse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedGates" upperBound="-1" eType="//Gate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionUse" eSuperTypes="//AbstractFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedScenario" eType="//Scenario" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" eSuperTypes="//AbstractFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" defaultValueLiteral="UNSET">
      <eType xsi:type="ecore:EEnum" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//InteractionOperatorKind"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedOperands" upperBound="-1" eType="//InteractionOperand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Execution" eSuperTypes="//TimeLapse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateFragment" eSuperTypes="//TimeLapse"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventReceiptOperation" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventSentOperation" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreationEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="DestructionEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArmTimerEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintDuratio">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="//InteractionFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finish" eType="//InteractionFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" defaultValueLiteral="UNSET">
      <eType xsi:type="ecore:EEnum" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//ScenarioKind"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstanceRoles" upperBound="-1" eType="//InstanceRole" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMessages" upperBound="-1" eType="//SequenceMessage" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInteractionFragments" upperBound="-1" eType="//InteractionFragment" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTimeLapses" upperBound="-1" eType="//TimeLapse" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEvents" upperBound="-1" eType="//Event" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConstraintDurations" upperBound="-1" eType="//ConstraintDuratio" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preCondition" eType="//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postCondition" eType="//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model__graph_sd" eSuperTypes="//GraphGen">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="序列图 [ graph_sd ] "/>
      <details key="self" value="graph_sd"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="序列图"/>
    </eAnnotations>
    <eAnnotations source="Binding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1" eType="//Tag__Layout__graph_sd" containment="true" eOpposite="//Tag__Layout__graph_sd/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1" eType="//Tag__Table__graph_sd" containment="true" eOpposite="//Tag__Table__graph_sd/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrixs" upperBound="-1" eType="//Tag__Matrix__graph_sd" containment="true" eOpposite="//Tag__Matrix__graph_sd/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gantts" upperBound="-1" eType="//Gantt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__graph_sd" containment="true" eOpposite="//Tag__Property__graph_sd/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1" eType="//Tag__Object__graph_sd" containment="true" eOpposite="//Tag__Object__graph_sd/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1" eType="//Tag__Relationship__graph_sd" containment="true" eOpposite="//Tag__Relationship__graph_sd/enclosingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Layout__graph_sd" eSuperTypes="//LayoutGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramKind" eType="//diagramKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementType" eType="//modelElementTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__graph_sd" eOpposite="//Model__graph_sd/layouts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagramKinds">
    <eLiterals name="bdd"/>
    <eLiterals name="idd" value="1"/>
    <eLiterals name="uc" value="2"/>
    <eLiterals name="act" value="3"/>
    <eLiterals name="sd" value="4"/>
    <eLiterals name="stm" value="5"/>
    <eLiterals name="par" value="6"/>
    <eLiterals name="req" value="7"/>
    <eLiterals name="pkg" value="8"/>
    <eLiterals name="annotation" value="9"/>
    <eLiterals name="others" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="modelElementTypes">
    <eLiterals name="package"/>
    <eLiterals name="model" value="1"/>
    <eLiterals name="modelLibrary" value="2"/>
    <eLiterals name="view" value="3"/>
    <eLiterals name="block" value="4"/>
    <eLiterals name="constraintBlock" value="5"/>
    <eLiterals name="activity" value="6"/>
    <eLiterals name="interaction" value="7"/>
    <eLiterals name="stateMachine" value="8"/>
    <eLiterals name="profile" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__layout" eSuperTypes="//Tag__Layout__graph_sd //LayoutGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="布局插件"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Table__graph_sd" eSuperTypes="//TableGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__graph_sd" eOpposite="//Model__graph_sd/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__table" eSuperTypes="//Tag__Table__graph_sd //TableGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Matrix__graph_sd" eSuperTypes="//MatrixGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__graph_sd" eOpposite="//Model__graph_sd/matrixs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__matrix" eSuperTypes="//Tag__Matrix__graph_sd //MatrixGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gantt" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="//times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTasks" upperBound="-1" eType="//GanttTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="times">
    <eLiterals name="YEAR"/>
    <eLiterals name="MONTH" value="1"/>
    <eLiterals name="DAY" value="2"/>
    <eLiterals name="HOUR" value="3"/>
    <eLiterals name="MINUTE" value="4"/>
    <eLiterals name="SECOND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__gantt" eSuperTypes="//Gantt"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTask" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTaskElements" upperBound="-1" eType="//GanttTaskElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__ganttTask" eSuperTypes="//GanttTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTaskElement" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementOffset">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementLength">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementColor">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__ganttTaskElement" eSuperTypes="//GanttTaskElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__graph_sd" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__graph_sd" eOpposite="//Model__graph_sd/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Object__graph_sd" abstract="true" eSuperTypes="//ObjectGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__graph_sd" eOpposite="//Model__graph_sd/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Relationship__graph_sd" abstract="true" eSuperTypes="//RelationshipGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__graph_sd" eOpposite="//Model__graph_sd/relationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__object_block" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="模块"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__object_block" containment="true" eOpposite="//Tag__Property__object_block/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__object_block" containment="true" eOpposite="//Tag__InputPoint__object_block/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__object_block" containment="true" eOpposite="//Tag__OutputPoint__object_block/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__object_block" containment="true" eOpposite="//Tag__UndirectedPoint__object_block/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__object_block" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_block" eOpposite="//Object__object_block/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__object_block" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_block" eOpposite="//Object__object_block/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__object_block" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_block" eOpposite="//Object__object_block/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__object_block" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_block" eOpposite="//Object__object_block/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__property_name" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="名称"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__object_block__object_block_property_name_c7eb65" eSuperTypes="//Property__property_name //Tag__Property__object_block">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="名称 [ object_block_property_name_c7eb65 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="名称"/>
      <details key="value" value="null"/>
      <details key="self" value="object_block_property_name_c7eb65"/>
      <details key="parent" value="object_block"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="名称"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__object_block_point_port_914a0f" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingPoint" ordered="false" lowerBound="1" eType="//Point__object_block_point_port_914a0f" eOpposite="//Point__object_block_point_port_914a0f/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point__object_block_point_port_914a0f" eSuperTypes="//UndirectedPointGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="端口"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__object_block_point_port_914a0f" containment="true" eOpposite="//Tag__Property__object_block_point_port_914a0f/enclosingPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__object_block__object_block_point_port_914a0f" eSuperTypes="//Tag__UndirectedPoint__object_block //Point__object_block_point_port_914a0f">
    <eAnnotations source="annotation">
      <details key="pointShape" value="rectangle"/>
      <details key="metaType" value="point_port"/>
      <details key="parent" value="object_block_point_port_914a0f"/>
      <details key="LocalLabel" value="端口"/>
      <details key="metaInfo" value="端口 [ object_block_point_port_914a0f ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="端口"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__object_lifelineobject" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="生命线对象"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__object_lifelineobject" containment="true" eOpposite="//Tag__Property__object_lifelineobject/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__object_lifelineobject" containment="true" eOpposite="//Tag__InputPoint__object_lifelineobject/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__object_lifelineobject" containment="true" eOpposite="//Tag__OutputPoint__object_lifelineobject/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__object_lifelineobject" containment="true" eOpposite="//Tag__UndirectedPoint__object_lifelineobject/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__object_lifelineobject" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_lifelineobject" eOpposite="//Object__object_lifelineobject/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__object_lifelineobject" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_lifelineobject" eOpposite="//Object__object_lifelineobject/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__object_lifelineobject" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_lifelineobject" eOpposite="//Object__object_lifelineobject/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__object_lifelineobject" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_lifelineobject" eOpposite="//Object__object_lifelineobject/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__property_text" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="描述"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__object_lifelineobject__object_lifelineobject_property_text_09dea4" eSuperTypes="//Property__property_text //Tag__Property__object_lifelineobject">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="描述 [ object_lifelineobject_property_text_09dea4 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="描述"/>
      <details key="value" value="null"/>
      <details key="self" value="object_lifelineobject_property_text_09dea4"/>
      <details key="parent" value="object_lifelineobject"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="描述"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__object_lifelineobject__object_lifelineobject_property_name_872eb4" eSuperTypes="//Property__property_name //Tag__Property__object_lifelineobject">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="名称 [ object_lifelineobject_property_name_872eb4 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="名称"/>
      <details key="value" value="null"/>
      <details key="self" value="object_lifelineobject_property_name_872eb4"/>
      <details key="parent" value="object_lifelineobject"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="名称"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__object_message" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__object_message" containment="true" eOpposite="//Tag__Property__object_message/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__object_message" containment="true" eOpposite="//Tag__InputPoint__object_message/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__object_message" containment="true" eOpposite="//Tag__OutputPoint__object_message/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__object_message" containment="true" eOpposite="//Tag__UndirectedPoint__object_message/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__object_message" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_message" eOpposite="//Object__object_message/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__object_message" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_message" eOpposite="//Object__object_message/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__object_message" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_message" eOpposite="//Object__object_message/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__object_message" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_message" eOpposite="//Object__object_message/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__object_message__object_message_property_name_06a112" eSuperTypes="//Property__property_name //Tag__Property__object_message">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="名称 [ object_message_property_name_06a112 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="名称"/>
      <details key="value" value="null"/>
      <details key="self" value="object_message_property_name_06a112"/>
      <details key="parent" value="object_message"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="名称"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__object_note" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="注释"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__object_note" containment="true" eOpposite="//Tag__Property__object_note/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__object_note" containment="true" eOpposite="//Tag__InputPoint__object_note/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__object_note" containment="true" eOpposite="//Tag__OutputPoint__object_note/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__object_note" containment="true" eOpposite="//Tag__UndirectedPoint__object_note/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__object_note" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_note" eOpposite="//Object__object_note/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__object_note" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_note" eOpposite="//Object__object_note/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__object_note" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_note" eOpposite="//Object__object_note/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__object_note" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__object_note" eOpposite="//Object__object_note/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__object_note__object_note_property_text_e7a2b5" eSuperTypes="//Property__property_text //Tag__Property__object_note">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="描述 [ object_note_property_text_e7a2b5 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="描述"/>
      <details key="value" value="null"/>
      <details key="self" value="object_note_property_text_e7a2b5"/>
      <details key="parent" value="object_note"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="描述"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_block" eSuperTypes="//Tag__Object__graph_sd //Object__object_block">
    <eAnnotations source="annotation">
      <details key="self" value="object_block"/>
      <details key="parent" value="graph_sd"/>
      <details key="mode" value="propertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="LocalLabel" value="模块"/>
      <details key="metaInfo" value="模块[object_block]"/>
      <details key="properties" value="Def__object_block__object_block_property_name_c7eb65,object_block_property_name_c7eb65,名称,null"/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value="Def__object_block__object_block_point_port_914a0f,object_block_point_port_914a0f,端口"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="模块"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__graph_sd__object_block__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__graph_sd__object_block__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_block__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_block__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_lifelineobject" eSuperTypes="//Tag__Object__graph_sd //Object__object_lifelineobject">
    <eAnnotations source="annotation">
      <details key="self" value="object_lifelineobject"/>
      <details key="parent" value="graph_sd"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="timingDiagramCharacterStyle"/>
      <details key="LocalLabel" value="生命线对象"/>
      <details key="metaInfo" value="生命线对象[object_lifelineobject]"/>
      <details key="properties" value="Def__object_lifelineobject__object_lifelineobject_property_text_09dea4,object_lifelineobject_property_text_09dea4,描述,null;Def__object_lifelineobject__object_lifelineobject_property_name_872eb4,object_lifelineobject_property_name_872eb4,名称,null"/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="生命线对象"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__graph_sd__object_lifelineobject__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__graph_sd__object_lifelineobject__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_lifelineobject__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_lifelineobject__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_message" eSuperTypes="//Tag__Object__graph_sd //Object__object_message">
    <eAnnotations source="annotation">
      <details key="self" value="object_message"/>
      <details key="parent" value="graph_sd"/>
      <details key="mode" value="propertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="LocalLabel" value="消息"/>
      <details key="metaInfo" value="消息[object_message]"/>
      <details key="properties" value="Def__object_message__object_message_property_name_06a112,object_message_property_name_06a112,名称,null"/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__graph_sd__object_message__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__graph_sd__object_message__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_message__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_message__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_note" eSuperTypes="//Tag__Object__graph_sd //Object__object_note">
    <eAnnotations source="annotation">
      <details key="self" value="object_note"/>
      <details key="parent" value="graph_sd"/>
      <details key="mode" value="containerMode"/>
      <details key="shape" value="rectangle"/>
      <details key="LocalLabel" value="注释"/>
      <details key="metaInfo" value="注释[object_note]"/>
      <details key="properties" value="Def__object_note__object_note_property_text_e7a2b5,object_note_property_text_e7a2b5,描述,null"/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="注释"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decompose" eType="//Def__graph_sd__object_note__decompose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodes" upperBound="-1" eType="//Def__graph_sd__object_note__explodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_note__decompose" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__object_note__explodes" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__create_message" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__create_message" eOpposite="//Relationship__create_message/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__create_message" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="创建消息"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__create_message" containment="true" eOpposite="//Tag__Property__create_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__create_message" containment="true" eOpposite="//Tag__Role__Import__create_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__create_message" containment="true" eOpposite="//Tag__Role__Export__create_message/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__create_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__create_message" eOpposite="//Relationship__create_message/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__create_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__create_message" eOpposite="//Relationship__create_message/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__information_In" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_In"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_In"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_In"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_In"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__create_message__information_In" eSuperTypes="//Tag__Role__Import__create_message //Role__information_In">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递始端 [ information_In ] "/>
      <details key="LocalLabel" value="消息传递始端"/>
      <details key="parent" value="create_message"/>
      <details key="self" value="information_In"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__information_In" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息传递始端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_In" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_In" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_In" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_In" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__information_Out" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_Out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_Out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_Out"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__information_Out"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__create_message__information_Out" eSuperTypes="//Tag__Role__Export__create_message //Role__information_Out">
    <eAnnotations source="annotation">
      <details key="shape" value="solidArrow"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递终端 [ information_Out ] "/>
      <details key="LocalLabel" value="消息传递终端"/>
      <details key="parent" value="create_message"/>
      <details key="self" value="information_Out"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__information_Out" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息传递终端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_Out" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_Out" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_Out" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__information_Out" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__create_message" eSuperTypes="//Tag__Relationship__graph_sd //Relationship__create_message">
    <eAnnotations source="annotation">
      <details key="parent" value="graph_sd"/>
      <details key="self" value="create_message"/>
      <details key="roles" value="information_In,information_Out"/>
      <details key="LocalLabel" value="创建消息"/>
      <details key="metaInfo" value="创建消息 [ create_message ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__pass_message" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__pass_message" eOpposite="//Relationship__pass_message/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__pass_message" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="传递消息"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__pass_message" containment="true" eOpposite="//Tag__Property__pass_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__pass_message" containment="true" eOpposite="//Tag__Role__Import__pass_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__pass_message" containment="true" eOpposite="//Tag__Role__Export__pass_message/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__pass_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__pass_message" eOpposite="//Relationship__pass_message/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__pass_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__pass_message" eOpposite="//Relationship__pass_message/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__pass_message__information_In" eSuperTypes="//Tag__Role__Import__pass_message //Role__information_In">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递始端 [ information_In ] "/>
      <details key="LocalLabel" value="消息传递始端"/>
      <details key="parent" value="pass_message"/>
      <details key="self" value="information_In"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__pass_message__information_Out" eSuperTypes="//Tag__Role__Export__pass_message //Role__information_Out">
    <eAnnotations source="annotation">
      <details key="shape" value="solidArrow"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递终端 [ information_Out ] "/>
      <details key="LocalLabel" value="消息传递终端"/>
      <details key="parent" value="pass_message"/>
      <details key="self" value="information_Out"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__pass_message" eSuperTypes="//Tag__Relationship__graph_sd //Relationship__pass_message">
    <eAnnotations source="annotation">
      <details key="parent" value="graph_sd"/>
      <details key="self" value="pass_message"/>
      <details key="roles" value="information_In,information_Out"/>
      <details key="LocalLabel" value="传递消息"/>
      <details key="metaInfo" value="传递消息 [ pass_message ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__reply_message" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__reply_message" eOpposite="//Relationship__reply_message/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__reply_message" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="回复消息"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__reply_message" containment="true" eOpposite="//Tag__Property__reply_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__reply_message" containment="true" eOpposite="//Tag__Role__Import__reply_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__reply_message" containment="true" eOpposite="//Tag__Role__Export__reply_message/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__reply_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__reply_message" eOpposite="//Relationship__reply_message/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__reply_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__reply_message" eOpposite="//Relationship__reply_message/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__reply_message__information_In" eSuperTypes="//Tag__Role__Import__reply_message //Role__information_In">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递始端 [ information_In ] "/>
      <details key="LocalLabel" value="消息传递始端"/>
      <details key="parent" value="reply_message"/>
      <details key="self" value="information_In"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__reply_message__information_Out" eSuperTypes="//Tag__Role__Export__reply_message //Role__information_Out">
    <eAnnotations source="annotation">
      <details key="shape" value="solidArrow"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递终端 [ information_Out ] "/>
      <details key="LocalLabel" value="消息传递终端"/>
      <details key="parent" value="reply_message"/>
      <details key="self" value="information_Out"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__reply_message" eSuperTypes="//Tag__Relationship__graph_sd //Relationship__reply_message">
    <eAnnotations source="annotation">
      <details key="parent" value="graph_sd"/>
      <details key="self" value="reply_message"/>
      <details key="roles" value="information_In,information_Out"/>
      <details key="LocalLabel" value="回复消息"/>
      <details key="metaInfo" value="回复消息 [ reply_message ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__send_message" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__send_message" eOpposite="//Relationship__send_message/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__send_message" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="发送消息"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__send_message" containment="true" eOpposite="//Tag__Property__send_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__send_message" containment="true" eOpposite="//Tag__Role__Import__send_message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__send_message" containment="true" eOpposite="//Tag__Role__Export__send_message/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__send_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__send_message" eOpposite="//Relationship__send_message/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__send_message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__send_message" eOpposite="//Relationship__send_message/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__send_message__information_In" eSuperTypes="//Tag__Role__Import__send_message //Role__information_In">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递始端 [ information_In ] "/>
      <details key="LocalLabel" value="消息传递始端"/>
      <details key="parent" value="send_message"/>
      <details key="self" value="information_In"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__send_message__information_Out" eSuperTypes="//Tag__Role__Export__send_message //Role__information_Out">
    <eAnnotations source="annotation">
      <details key="shape" value="solidArrow"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息传递终端 [ information_Out ] "/>
      <details key="LocalLabel" value="消息传递终端"/>
      <details key="parent" value="send_message"/>
      <details key="self" value="information_Out"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__send_message" eSuperTypes="//Tag__Relationship__graph_sd //Relationship__send_message">
    <eAnnotations source="annotation">
      <details key="parent" value="graph_sd"/>
      <details key="self" value="send_message"/>
      <details key="roles" value="information_In,information_Out"/>
      <details key="LocalLabel" value="发送消息"/>
      <details key="metaInfo" value="发送消息 [ send_message ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__association" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__association" eOpposite="//Relationship__association/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__association" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关联"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__association" containment="true" eOpposite="//Tag__Property__association/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__association" containment="true" eOpposite="//Tag__Role__Import__association/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__association" containment="true" eOpposite="//Tag__Role__Export__association/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__association" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__association" eOpposite="//Relationship__association/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__association" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__association" eOpposite="//Relationship__association/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__association_In" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__association_In"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__association__association_In" eSuperTypes="//Tag__Role__Import__association //Role__association_In">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关联始端 [ association_In ] "/>
      <details key="LocalLabel" value="关联始端"/>
      <details key="parent" value="association"/>
      <details key="self" value="association_In"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__association_In" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关联始端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__association_In" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__association_Out" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__association_Out"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__association__association_Out" eSuperTypes="//Tag__Role__Export__association //Role__association_Out">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关联终端 [ association_Out ] "/>
      <details key="LocalLabel" value="关联终端"/>
      <details key="parent" value="association"/>
      <details key="self" value="association_Out"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__association_Out" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关联终端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__association_Out" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__graph_sd__association" eSuperTypes="//Tag__Relationship__graph_sd //Relationship__association">
    <eAnnotations source="annotation">
      <details key="parent" value="graph_sd"/>
      <details key="self" value="association"/>
      <details key="roles" value="association_In,association_Out"/>
      <details key="LocalLabel" value="关联"/>
      <details key="metaInfo" value="关联 [ association ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
