<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="k0f1ebdebb4" nsURI="D:/Office/MetaGraph20241130_208zjs/ArchModeling/workspace/城市智慧管理-体系V1.0/语言/体系/图元模型/k0f1ebdebb4.karma"
    nsPrefix="k0f1ebdebb4">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltIn" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KMatrix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPlugin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPointGen" eSuperTypes="#//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPointGen" eSuperTypes="#//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedPointGen" eSuperTypes="#//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportRoleGen" eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportRoleGen" eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTable"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableRow"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableCell"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model__k0f1ebdebb4" eSuperTypes="#//GraphGen">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="场景分解 [ k0f1ebdebb4 ] "/>
      <details key="self" value="k0f1ebdebb4"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="场景分解"/>
    </eAnnotations>
    <eAnnotations source="Binding">
      <details key="sourceRule" value="Def__k0f1ebdebb4__k214aa4d85e->Def__k9276a624df__kcacc7992eb"/>
      <details key="targetRule" value="Def__k0f1ebdebb4__k214aa4d85e->Def__k9276a624df__k635b59ddfd"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1"
        eType="#//Tag__Layout__k0f1ebdebb4" containment="true" eOpposite="#//Tag__Layout__k0f1ebdebb4/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Tag__Table__k0f1ebdebb4" containment="true" eOpposite="#//Tag__Table__k0f1ebdebb4/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrixs" upperBound="-1"
        eType="#//Tag__Matrix__k0f1ebdebb4" containment="true" eOpposite="#//Tag__Matrix__k0f1ebdebb4/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gantts" upperBound="-1"
        eType="#//Gantt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__k0f1ebdebb4" containment="true" eOpposite="#//Tag__Property__k0f1ebdebb4/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//Tag__Object__k0f1ebdebb4" containment="true" eOpposite="#//Tag__Object__k0f1ebdebb4/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Tag__Relationship__k0f1ebdebb4" containment="true" eOpposite="#//Tag__Relationship__k0f1ebdebb4/enclosingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Layout__k0f1ebdebb4" eSuperTypes="#//LayoutGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramKind" eType="#//diagramKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementType" eType="#//modelElementTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k0f1ebdebb4" eOpposite="#//Model__k0f1ebdebb4/layouts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagramKinds">
    <eLiterals name="bdd"/>
    <eLiterals name="idd" value="1"/>
    <eLiterals name="uc" value="2"/>
    <eLiterals name="act" value="3"/>
    <eLiterals name="sd" value="4"/>
    <eLiterals name="stm" value="5"/>
    <eLiterals name="par" value="6"/>
    <eLiterals name="req" value="7"/>
    <eLiterals name="pkg" value="8"/>
    <eLiterals name="annotation" value="9"/>
    <eLiterals name="others" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="modelElementTypes">
    <eLiterals name="package"/>
    <eLiterals name="model" value="1"/>
    <eLiterals name="modelLibrary" value="2"/>
    <eLiterals name="view" value="3"/>
    <eLiterals name="block" value="4"/>
    <eLiterals name="constraintBlock" value="5"/>
    <eLiterals name="activity" value="6"/>
    <eLiterals name="interaction" value="7"/>
    <eLiterals name="stateMachine" value="8"/>
    <eLiterals name="profile" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__layout" eSuperTypes="#//Tag__Layout__k0f1ebdebb4 #//LayoutGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="布局插件"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Table__k0f1ebdebb4" eSuperTypes="#//TableGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k0f1ebdebb4" eOpposite="#//Model__k0f1ebdebb4/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__table" eSuperTypes="#//Tag__Table__k0f1ebdebb4 #//TableGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Matrix__k0f1ebdebb4" eSuperTypes="#//MatrixGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k0f1ebdebb4" eOpposite="#//Model__k0f1ebdebb4/matrixs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__matrix" eSuperTypes="#//Tag__Matrix__k0f1ebdebb4 #//MatrixGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gantt" eSuperTypes="#//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="#//times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTasks" upperBound="-1"
        eType="#//GanttTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="times">
    <eLiterals name="YEAR"/>
    <eLiterals name="MONTH" value="1"/>
    <eLiterals name="DAY" value="2"/>
    <eLiterals name="HOUR" value="3"/>
    <eLiterals name="MINUTE" value="4"/>
    <eLiterals name="SECOND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__gantt" eSuperTypes="#//Gantt"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTask" abstract="true" eSuperTypes="#//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTaskElements" upperBound="-1"
        eType="#//GanttTaskElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__ganttTask" eSuperTypes="#//GanttTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTaskElement" abstract="true" eSuperTypes="#//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__ganttTaskElement"
      eSuperTypes="#//GanttTaskElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k0f1ebdebb4" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k0f1ebdebb4" eOpposite="#//Model__k0f1ebdebb4/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Object__k0f1ebdebb4" abstract="true"
      eSuperTypes="#//ObjectGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k0f1ebdebb4" eOpposite="#//Model__k0f1ebdebb4/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Relationship__k0f1ebdebb4" abstract="true"
      eSuperTypes="#//RelationshipGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k0f1ebdebb4" eOpposite="#//Model__k0f1ebdebb4/relationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__k214aa4d85e" abstract="true"
      eSuperTypes="#//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="任务场景"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__k214aa4d85e" containment="true" eOpposite="#//Tag__Property__k214aa4d85e/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Tag__InputPoint__k214aa4d85e" containment="true" eOpposite="#//Tag__InputPoint__k214aa4d85e/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Tag__OutputPoint__k214aa4d85e" containment="true" eOpposite="#//Tag__OutputPoint__k214aa4d85e/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1"
        eType="#//Tag__UndirectedPoint__k214aa4d85e" containment="true" eOpposite="#//Tag__UndirectedPoint__k214aa4d85e/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k214aa4d85e" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__k214aa4d85e" eOpposite="#//Object__k214aa4d85e/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__k214aa4d85e" abstract="true"
      eSuperTypes="#//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__k214aa4d85e" eOpposite="#//Object__k214aa4d85e/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__k214aa4d85e" abstract="true"
      eSuperTypes="#//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__k214aa4d85e" eOpposite="#//Object__k214aa4d85e/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__k214aa4d85e" abstract="true"
      eSuperTypes="#//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__k214aa4d85e" eOpposite="#//Object__k214aa4d85e/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__k214aa4d85e" eSuperTypes="#//Tag__Object__k0f1ebdebb4 #//Object__k214aa4d85e">
    <eAnnotations source="annotation">
      <details key="self" value="k214aa4d85e"/>
      <details key="parent" value="k0f1ebdebb4"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="任务场景[k214aa4d85e]"/>
      <details key="properties" value=""/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="任务场景"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="#//Def__k0f1ebdebb4__k214aa4d85e__decomposeN"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1"
        eType="#//Def__k0f1ebdebb4__k214aa4d85e__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__k214aa4d85e__decomposeN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__k214aa4d85e__explodesN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k9276a624df" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship"
        ordered="false" lowerBound="1" eType="#//Relationship__k9276a624df" eOpposite="#//Relationship__k9276a624df/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__k9276a624df" eSuperTypes="#//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="定向组合"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__k9276a624df" containment="true" eOpposite="#//Tag__Property__k9276a624df/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="#//Tag__Role__Import__k9276a624df"
        containment="true" eOpposite="#//Tag__Role__Import__k9276a624df/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="#//Tag__Role__Export__k9276a624df"
        containment="true" eOpposite="#//Tag__Role__Export__k9276a624df/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__k9276a624df" abstract="true"
      eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship"
        ordered="false" lowerBound="1" eType="#//Relationship__k9276a624df" eOpposite="#//Relationship__k9276a624df/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__k9276a624df" abstract="true"
      eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship"
        ordered="false" lowerBound="1" eType="#//Relationship__k9276a624df" eOpposite="#//Relationship__k9276a624df/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__kcacc7992eb" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false"
        lowerBound="1" eType="#//Role__kcacc7992eb"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9276a624df__kcacc7992eb" eSuperTypes="#//Tag__Role__Import__k9276a624df #//Role__kcacc7992eb">
    <eAnnotations source="annotation">
      <details key="shape" value="solidDiamond"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="定向组合始端 [ kcacc7992eb ] "/>
      <details key="parent" value="k9276a624df"/>
      <details key="self" value="kcacc7992eb"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__kcacc7992eb" eSuperTypes="#//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="定向组合始端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__kcacc7992eb" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k635b59ddfd" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false"
        lowerBound="1" eType="#//Role__k635b59ddfd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9276a624df__k635b59ddfd" eSuperTypes="#//Tag__Role__Export__k9276a624df #//Role__k635b59ddfd">
    <eAnnotations source="annotation">
      <details key="shape" value="arrowShape"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="定向组合终端 [ k635b59ddfd ] "/>
      <details key="parent" value="k9276a624df"/>
      <details key="self" value="k635b59ddfd"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__k635b59ddfd" eSuperTypes="#//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="定向组合终端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__k635b59ddfd" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k0f1ebdebb4__k9276a624df" eSuperTypes="#//Tag__Relationship__k0f1ebdebb4 #//Relationship__k9276a624df">
    <eAnnotations source="annotation">
      <details key="parent" value="k0f1ebdebb4"/>
      <details key="self" value="k9276a624df"/>
      <details key="roles" value="kcacc7992eb,k635b59ddfd"/>
      <details key="metaInfo" value="定向组合 [ k9276a624df ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="k287008c10c" instanceTypeName="k214aa4d85e"/>
  <eClassifiers xsi:type="ecore:EClass" name="kce808dff5e_object_ed0c" instanceTypeName="k214aa4d85e"/>
  <eClassifiers xsi:type="ecore:EClass" name="kce808dff5e_object_ac48" instanceTypeName="k214aa4d85e"/>
  <eClassifiers xsi:type="ecore:EClass" name="kce808dff5e_object_6383" instanceTypeName="k214aa4d85e"/>
  <eClassifiers xsi:type="ecore:EClass" name="kce808dff5e_object_1d62" instanceTypeName="k214aa4d85e"/>
  <eClassifiers xsi:type="ecore:EClass" name="k1eb5de8199" instanceTypeName="k79433291a1"/>
  <eClassifiers xsi:type="ecore:EClass" name="kf48d72fb31" instanceTypeName="k79433291a1"/>
  <eClassifiers xsi:type="ecore:EClass" name="kd8951c6670" instanceTypeName="k79433291a1"/>
  <eClassifiers xsi:type="ecore:EClass" name="k21012e1e51" instanceTypeName="k79433291a1"/>
  <eClassifiers xsi:type="ecore:EClass" name="ka9cf47a48a" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k5e4e3d4047" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k7526bfdc04" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k6818db5a64" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k4ebe86edd9" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="kb8ebd56854" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k606eb8a486" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k130033c689" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k120a5f5a97" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k305bed717f" instanceTypeName="k6651ca9f0a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k479fc30ea9" instanceTypeName="k98f5faf528"/>
  <eClassifiers xsi:type="ecore:EClass" name="kd4be9235c8" instanceTypeName="kc89d572a5a"/>
  <eClassifiers xsi:type="ecore:EClass" name="kd5bca04493" instanceTypeName="kbf8d32351a"/>
  <eClassifiers xsi:type="ecore:EClass" name="k725032caa6" instanceTypeName="kf4f5773162"/>
  <eClassifiers xsi:type="ecore:EClass" name="kf4c77e49c7" instanceTypeName="k06a5bc2a7b"/>
  <eClassifiers xsi:type="ecore:EClass" name="k98e96ca523" instanceTypeName="ke6855759bb"/>
  <eClassifiers xsi:type="ecore:EClass" name="ka2fdc0a5e1" instanceTypeName="k696ccb6e90"/>
  <eClassifiers xsi:type="ecore:EClass" name="kef5f65b771" instanceTypeName="k9c77780d55"/>
  <eClassifiers xsi:type="ecore:EClass" name="k97572cb888" instanceTypeName="k7348a2eb4c"/>
  <eClassifiers xsi:type="ecore:EClass" name="ke12928f6c0" instanceTypeName="ked5f782f6a"/>
</ecore:EPackage>
