<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="k76fcf9c885" nsURI="D:/Office/MetaGraph20241130_208zjs/ArchModeling/workspace/城市智慧管理-体系V1.0/语言/体系/图元模型/k76fcf9c885.karma" nsPrefix="k76fcf9c885">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltIn">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KLayout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KMatrix"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPlugin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model__k76fcf9c885" eSuperTypes="//GraphGen">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="能力追溯智慧体系要素 [ k76fcf9c885 ] "/>
      <details key="self" value="k76fcf9c885"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="能力追溯智慧体系要素"/>
    </eAnnotations>
    <eAnnotations source="Binding"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1" eType="//Tag__Layout__k76fcf9c885" containment="true" eOpposite="//Tag__Layout__k76fcf9c885/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1" eType="//Tag__Table__k76fcf9c885" containment="true" eOpposite="//Tag__Table__k76fcf9c885/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrixs" upperBound="-1" eType="//Tag__Matrix__k76fcf9c885" containment="true" eOpposite="//Tag__Matrix__k76fcf9c885/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gantts" upperBound="-1" eType="//Gantt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k76fcf9c885" containment="true" eOpposite="//Tag__Property__k76fcf9c885/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1" eType="//Tag__Object__k76fcf9c885" containment="true" eOpposite="//Tag__Object__k76fcf9c885/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1" eType="//Tag__Relationship__k76fcf9c885" containment="true" eOpposite="//Tag__Relationship__k76fcf9c885/enclosingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Layout__k76fcf9c885" eSuperTypes="//LayoutGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramKind" eType="//diagramKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementType" eType="//modelElementTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k76fcf9c885" eOpposite="//Model__k76fcf9c885/layouts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagramKinds">
    <eLiterals name="bdd"/>
    <eLiterals name="idd" value="1"/>
    <eLiterals name="uc" value="2"/>
    <eLiterals name="act" value="3"/>
    <eLiterals name="sd" value="4"/>
    <eLiterals name="stm" value="5"/>
    <eLiterals name="par" value="6"/>
    <eLiterals name="req" value="7"/>
    <eLiterals name="pkg" value="8"/>
    <eLiterals name="annotation" value="9"/>
    <eLiterals name="others" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="modelElementTypes">
    <eLiterals name="package"/>
    <eLiterals name="model" value="1"/>
    <eLiterals name="modelLibrary" value="2"/>
    <eLiterals name="view" value="3"/>
    <eLiterals name="block" value="4"/>
    <eLiterals name="constraintBlock" value="5"/>
    <eLiterals name="activity" value="6"/>
    <eLiterals name="interaction" value="7"/>
    <eLiterals name="stateMachine" value="8"/>
    <eLiterals name="profile" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k76fcf9c885__layout" eSuperTypes="//Tag__Layout__k76fcf9c885 //LayoutGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="布局插件"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Table__k76fcf9c885" eSuperTypes="//TableGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k76fcf9c885" eOpposite="//Model__k76fcf9c885/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k76fcf9c885__table" eSuperTypes="//Tag__Table__k76fcf9c885 //TableGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Matrix__k76fcf9c885" eSuperTypes="//MatrixGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k76fcf9c885" eOpposite="//Model__k76fcf9c885/matrixs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k76fcf9c885__matrix" eSuperTypes="//Tag__Matrix__k76fcf9c885 //MatrixGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gantt" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="//times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTasks" upperBound="-1" eType="//GanttTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="times">
    <eLiterals name="YEAR"/>
    <eLiterals name="MONTH" value="1"/>
    <eLiterals name="DAY" value="2"/>
    <eLiterals name="HOUR" value="3"/>
    <eLiterals name="MINUTE" value="4"/>
    <eLiterals name="SECOND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k76fcf9c885__gantt" eSuperTypes="//Gantt"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTask" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTaskElements" upperBound="-1" eType="//GanttTaskElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k76fcf9c885__ganttTask" eSuperTypes="//GanttTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTaskElement" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementOffset">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementLength">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementColor">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k76fcf9c885__ganttTaskElement" eSuperTypes="//GanttTaskElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k76fcf9c885" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k76fcf9c885" eOpposite="//Model__k76fcf9c885/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Object__k76fcf9c885" abstract="true" eSuperTypes="//ObjectGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k76fcf9c885" eOpposite="//Model__k76fcf9c885/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Relationship__k76fcf9c885" abstract="true" eSuperTypes="//RelationshipGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k76fcf9c885" eOpposite="//Model__k76fcf9c885/relationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k82c7f446d4" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__k82c7f446d4" eOpposite="//Relationship__k82c7f446d4/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__k82c7f446d4" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="追溯"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k82c7f446d4" containment="true" eOpposite="//Tag__Property__k82c7f446d4/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__k82c7f446d4" containment="true" eOpposite="//Tag__Role__Import__k82c7f446d4/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__k82c7f446d4" containment="true" eOpposite="//Tag__Role__Export__k82c7f446d4/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__k82c7f446d4" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__k82c7f446d4" eOpposite="//Relationship__k82c7f446d4/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__k82c7f446d4" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__k82c7f446d4" eOpposite="//Relationship__k82c7f446d4/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k6538ec61e1" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__k6538ec61e1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k82c7f446d4__k6538ec61e1" eSuperTypes="//Tag__Role__Import__k82c7f446d4 //Role__k6538ec61e1">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关系始端 [ k6538ec61e1 ] "/>
      <details key="parent" value="k82c7f446d4"/>
      <details key="self" value="k6538ec61e1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__k6538ec61e1" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关系始端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k6538ec61e1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__kf2004d8ed5" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__kf2004d8ed5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k82c7f446d4__kf2004d8ed5" eSuperTypes="//Tag__Role__Export__k82c7f446d4 //Role__kf2004d8ed5">
    <eAnnotations source="annotation">
      <details key="shape" value="arrowShape"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关系终端 [ kf2004d8ed5 ] "/>
      <details key="parent" value="k82c7f446d4"/>
      <details key="self" value="kf2004d8ed5"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__kf2004d8ed5" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关系终端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__kf2004d8ed5" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k76fcf9c885__k82c7f446d4" eSuperTypes="//Tag__Relationship__k76fcf9c885 //Relationship__k82c7f446d4">
    <eAnnotations source="annotation">
      <details key="parent" value="k76fcf9c885"/>
      <details key="self" value="k82c7f446d4"/>
      <details key="roles" value="k6538ec61e1,kf2004d8ed5"/>
      <details key="metaInfo" value="追溯 [ k82c7f446d4 ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
