<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="k8b3baa8fa9" nsURI="D:/Office/MetaGraph20241130_208zjs/ArchModeling/workspace/城市智慧管理-体系V1.0/语言/体系/图元模型/k8b3baa8fa9.karma" nsPrefix="k8b3baa8fa9">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltIn">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KLayout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KMatrix"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPlugin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model__k8b3baa8fa9" eSuperTypes="//GraphGen">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="兴趣系统能力效果分析 [ k8b3baa8fa9 ] "/>
      <details key="self" value="k8b3baa8fa9"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="兴趣系统能力效果分析"/>
    </eAnnotations>
    <eAnnotations source="Binding">
      <details key="sourceRule" value="Def__k8b3baa8fa9__k79433291a1->Def__kd41b3b8ad7__k6538ec61e1"/>
      <details key="targetRule" value="Def__k8b3baa8fa9__k348b2b31b6->Def__kd41b3b8ad7__kf2004d8ed5"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1" eType="//Tag__Layout__k8b3baa8fa9" containment="true" eOpposite="//Tag__Layout__k8b3baa8fa9/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1" eType="//Tag__Table__k8b3baa8fa9" containment="true" eOpposite="//Tag__Table__k8b3baa8fa9/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrixs" upperBound="-1" eType="//Tag__Matrix__k8b3baa8fa9" containment="true" eOpposite="//Tag__Matrix__k8b3baa8fa9/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gantts" upperBound="-1" eType="//Gantt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k8b3baa8fa9" containment="true" eOpposite="//Tag__Property__k8b3baa8fa9/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1" eType="//Tag__Object__k8b3baa8fa9" containment="true" eOpposite="//Tag__Object__k8b3baa8fa9/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1" eType="//Tag__Relationship__k8b3baa8fa9" containment="true" eOpposite="//Tag__Relationship__k8b3baa8fa9/enclosingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Layout__k8b3baa8fa9" eSuperTypes="//LayoutGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramKind" eType="//diagramKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementType" eType="//modelElementTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k8b3baa8fa9" eOpposite="//Model__k8b3baa8fa9/layouts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagramKinds">
    <eLiterals name="bdd"/>
    <eLiterals name="idd" value="1"/>
    <eLiterals name="uc" value="2"/>
    <eLiterals name="act" value="3"/>
    <eLiterals name="sd" value="4"/>
    <eLiterals name="stm" value="5"/>
    <eLiterals name="par" value="6"/>
    <eLiterals name="req" value="7"/>
    <eLiterals name="pkg" value="8"/>
    <eLiterals name="annotation" value="9"/>
    <eLiterals name="others" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="modelElementTypes">
    <eLiterals name="package"/>
    <eLiterals name="model" value="1"/>
    <eLiterals name="modelLibrary" value="2"/>
    <eLiterals name="view" value="3"/>
    <eLiterals name="block" value="4"/>
    <eLiterals name="constraintBlock" value="5"/>
    <eLiterals name="activity" value="6"/>
    <eLiterals name="interaction" value="7"/>
    <eLiterals name="stateMachine" value="8"/>
    <eLiterals name="profile" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__layout" eSuperTypes="//Tag__Layout__k8b3baa8fa9 //LayoutGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="布局插件"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Table__k8b3baa8fa9" eSuperTypes="//TableGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k8b3baa8fa9" eOpposite="//Model__k8b3baa8fa9/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__table" eSuperTypes="//Tag__Table__k8b3baa8fa9 //TableGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Matrix__k8b3baa8fa9" eSuperTypes="//MatrixGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k8b3baa8fa9" eOpposite="//Model__k8b3baa8fa9/matrixs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__matrix" eSuperTypes="//Tag__Matrix__k8b3baa8fa9 //MatrixGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gantt" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="//times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTasks" upperBound="-1" eType="//GanttTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="times">
    <eLiterals name="YEAR"/>
    <eLiterals name="MONTH" value="1"/>
    <eLiterals name="DAY" value="2"/>
    <eLiterals name="HOUR" value="3"/>
    <eLiterals name="MINUTE" value="4"/>
    <eLiterals name="SECOND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__gantt" eSuperTypes="//Gantt"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTask" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTaskElements" upperBound="-1" eType="//GanttTaskElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__ganttTask" eSuperTypes="//GanttTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTaskElement" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementOffset">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementLength">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementColor">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__ganttTaskElement" eSuperTypes="//GanttTaskElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k8b3baa8fa9" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k8b3baa8fa9" eOpposite="//Model__k8b3baa8fa9/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Object__k8b3baa8fa9" abstract="true" eSuperTypes="//ObjectGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k8b3baa8fa9" eOpposite="//Model__k8b3baa8fa9/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Relationship__k8b3baa8fa9" abstract="true" eSuperTypes="//RelationshipGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__k8b3baa8fa9" eOpposite="//Model__k8b3baa8fa9/relationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__k348b2b31b6" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="能力效果"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k348b2b31b6" containment="true" eOpposite="//Tag__Property__k348b2b31b6/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__k348b2b31b6" containment="true" eOpposite="//Tag__InputPoint__k348b2b31b6/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__k348b2b31b6" containment="true" eOpposite="//Tag__OutputPoint__k348b2b31b6/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__k348b2b31b6" containment="true" eOpposite="//Tag__UndirectedPoint__k348b2b31b6/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k348b2b31b6" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k348b2b31b6" eOpposite="//Object__k348b2b31b6/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__k348b2b31b6" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k348b2b31b6" eOpposite="//Object__k348b2b31b6/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__k348b2b31b6" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k348b2b31b6" eOpposite="//Object__k348b2b31b6/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__k348b2b31b6" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k348b2b31b6" eOpposite="//Object__k348b2b31b6/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__BUILTIN_Object_Transfer_k79433291a1" abstract="true" eSuperTypes="//ObjectGen //BuiltIn">
    <eAnnotations source="LocalLabel">
      <details key="name" value="智慧体系要素"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__BUILTIN_Object_Transfer_k79433291a1" containment="true" eOpposite="//Tag__Property__BUILTIN_Object_Transfer_k79433291a1/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__BUILTIN_Object_Transfer_k79433291a1" containment="true" eOpposite="//Tag__InputPoint__BUILTIN_Object_Transfer_k79433291a1/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__BUILTIN_Object_Transfer_k79433291a1" containment="true" eOpposite="//Tag__OutputPoint__BUILTIN_Object_Transfer_k79433291a1/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__BUILTIN_Object_Transfer_k79433291a1" containment="true" eOpposite="//Tag__UndirectedPoint__BUILTIN_Object_Transfer_k79433291a1/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__BUILTIN_Object_Transfer_k79433291a1" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k79433291a1" eOpposite="//Object__BUILTIN_Object_Transfer_k79433291a1/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__BUILTIN_Object_Transfer_k79433291a1" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k79433291a1" eOpposite="//Object__BUILTIN_Object_Transfer_k79433291a1/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__BUILTIN_Object_Transfer_k79433291a1" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k79433291a1" eOpposite="//Object__BUILTIN_Object_Transfer_k79433291a1/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__BUILTIN_Object_Transfer_k79433291a1" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k79433291a1" eOpposite="//Object__BUILTIN_Object_Transfer_k79433291a1/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__k79433291a1" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="智慧体系要素"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k79433291a1" containment="true" eOpposite="//Tag__Property__k79433291a1/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__k79433291a1" containment="true" eOpposite="//Tag__InputPoint__k79433291a1/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__k79433291a1" containment="true" eOpposite="//Tag__OutputPoint__k79433291a1/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__k79433291a1" containment="true" eOpposite="//Tag__UndirectedPoint__k79433291a1/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k79433291a1" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k79433291a1" eOpposite="//Object__k79433291a1/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__k79433291a1" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k79433291a1" eOpposite="//Object__k79433291a1/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__k79433291a1" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k79433291a1" eOpposite="//Object__k79433291a1/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__k79433291a1" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__k79433291a1" eOpposite="//Object__k79433291a1/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k79433291a1_kb10cf08e6a_da02a1" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingPoint" ordered="false" lowerBound="1" eType="//Point__k79433291a1_kb10cf08e6a_da02a1" eOpposite="//Point__k79433291a1_kb10cf08e6a_da02a1/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point__k79433291a1_kb10cf08e6a_da02a1" eSuperTypes="//InputPointGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输入"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k79433291a1_kb10cf08e6a_da02a1" containment="true" eOpposite="//Tag__Property__k79433291a1_kb10cf08e6a_da02a1/enclosingPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k79433291a1__k79433291a1_kb10cf08e6a_da02a1" eSuperTypes="//Tag__InputPoint__k79433291a1 //Point__k79433291a1_kb10cf08e6a_da02a1">
    <eAnnotations source="annotation">
      <details key="pointShape" value="triangle"/>
      <details key="parent" value="k79433291a1"/>
      <details key="self" value="k79433291a1_kb10cf08e6a_da02a1"/>
      <details key="metaInfo" value="通信中继输入 [ k79433291a1_kb10cf08e6a_da02a1 ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输入"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k79433291a1_kb76db55211_8ec3ed" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingPoint" ordered="false" lowerBound="1" eType="//Point__k79433291a1_kb76db55211_8ec3ed" eOpposite="//Point__k79433291a1_kb76db55211_8ec3ed/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point__k79433291a1_kb76db55211_8ec3ed" eSuperTypes="//OutputPointGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输出"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k79433291a1_kb76db55211_8ec3ed" containment="true" eOpposite="//Tag__Property__k79433291a1_kb76db55211_8ec3ed/enclosingPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k79433291a1__k79433291a1_kb76db55211_8ec3ed" eSuperTypes="//Tag__OutputPoint__k79433291a1 //Point__k79433291a1_kb76db55211_8ec3ed">
    <eAnnotations source="annotation">
      <details key="pointShape" value="triangle"/>
      <details key="parent" value="k79433291a1"/>
      <details key="self" value="k79433291a1_kb76db55211_8ec3ed"/>
      <details key="metaInfo" value="通信中继输出 [ k79433291a1_kb76db55211_8ec3ed ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输出"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__BUILTIN_Object_Transfer_k348b2b31b6" abstract="true" eSuperTypes="//ObjectGen //BuiltIn">
    <eAnnotations source="LocalLabel">
      <details key="name" value="能力效果"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__BUILTIN_Object_Transfer_k348b2b31b6" containment="true" eOpposite="//Tag__Property__BUILTIN_Object_Transfer_k348b2b31b6/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__BUILTIN_Object_Transfer_k348b2b31b6" containment="true" eOpposite="//Tag__InputPoint__BUILTIN_Object_Transfer_k348b2b31b6/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__BUILTIN_Object_Transfer_k348b2b31b6" containment="true" eOpposite="//Tag__OutputPoint__BUILTIN_Object_Transfer_k348b2b31b6/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__BUILTIN_Object_Transfer_k348b2b31b6" containment="true" eOpposite="//Tag__UndirectedPoint__BUILTIN_Object_Transfer_k348b2b31b6/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__BUILTIN_Object_Transfer_k348b2b31b6" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k348b2b31b6" eOpposite="//Object__BUILTIN_Object_Transfer_k348b2b31b6/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__BUILTIN_Object_Transfer_k348b2b31b6" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k348b2b31b6" eOpposite="//Object__BUILTIN_Object_Transfer_k348b2b31b6/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__BUILTIN_Object_Transfer_k348b2b31b6" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k348b2b31b6" eOpposite="//Object__BUILTIN_Object_Transfer_k348b2b31b6/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__BUILTIN_Object_Transfer_k348b2b31b6" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__BUILTIN_Object_Transfer_k348b2b31b6" eOpposite="//Object__BUILTIN_Object_Transfer_k348b2b31b6/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__k348b2b31b6" eSuperTypes="//Tag__Object__k8b3baa8fa9 //Object__k348b2b31b6">
    <eAnnotations source="annotation">
      <details key="self" value="k348b2b31b6"/>
      <details key="parent" value="k8b3baa8fa9"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="能力效果[k348b2b31b6]"/>
      <details key="properties" value=""/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="能力效果"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__k8b3baa8fa9__k348b2b31b6__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__k8b3baa8fa9__k348b2b31b6__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__k348b2b31b6__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__k348b2b31b6__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k79433291a1" eSuperTypes="//Tag__Object__k8b3baa8fa9 //Object__BUILTIN_Object_Transfer_k79433291a1">
    <eAnnotations source="annotation">
      <details key="self" value="BUILTIN_Object_Transfer_k79433291a1"/>
      <details key="parent" value="k8b3baa8fa9"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="智慧体系要素[BUILTIN_Object_Transfer_k79433291a1]"/>
      <details key="properties" value=""/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
      <details key="referedMetaObject" value="k79433291a1"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="智慧体系要素"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k79433291a1__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k79433291a1__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k79433291a1__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k79433291a1__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__k79433291a1" eSuperTypes="//Tag__Object__k8b3baa8fa9 //Object__k79433291a1">
    <eAnnotations source="annotation">
      <details key="self" value="k79433291a1"/>
      <details key="parent" value="k8b3baa8fa9"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="智慧体系要素[k79433291a1]"/>
      <details key="properties" value=""/>
      <details key="input" value="Def__k79433291a1__k79433291a1_kb10cf08e6a_da02a1,k79433291a1_kb10cf08e6a_da02a1,通信中继输入"/>
      <details key="output" value="Def__k79433291a1__k79433291a1_kb76db55211_8ec3ed,k79433291a1_kb76db55211_8ec3ed,通信中继输出"/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="智慧体系要素"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__k8b3baa8fa9__k79433291a1__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__k8b3baa8fa9__k79433291a1__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__k79433291a1__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__k79433291a1__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k348b2b31b6" eSuperTypes="//Tag__Object__k8b3baa8fa9 //Object__BUILTIN_Object_Transfer_k348b2b31b6">
    <eAnnotations source="annotation">
      <details key="self" value="BUILTIN_Object_Transfer_k348b2b31b6"/>
      <details key="parent" value="k8b3baa8fa9"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="能力效果[BUILTIN_Object_Transfer_k348b2b31b6]"/>
      <details key="properties" value=""/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
      <details key="referedMetaObject" value="k348b2b31b6"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="能力效果"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k348b2b31b6__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k348b2b31b6__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k348b2b31b6__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__BUILTIN_Object_Transfer_k348b2b31b6__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__kd41b3b8ad7" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__kd41b3b8ad7" eOpposite="//Relationship__kd41b3b8ad7/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__kd41b3b8ad7" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="具备"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__kd41b3b8ad7" containment="true" eOpposite="//Tag__Property__kd41b3b8ad7/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__kd41b3b8ad7" containment="true" eOpposite="//Tag__Role__Import__kd41b3b8ad7/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__kd41b3b8ad7" containment="true" eOpposite="//Tag__Role__Export__kd41b3b8ad7/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__kd41b3b8ad7" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__kd41b3b8ad7" eOpposite="//Relationship__kd41b3b8ad7/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__kd41b3b8ad7" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__kd41b3b8ad7" eOpposite="//Relationship__kd41b3b8ad7/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k6538ec61e1" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__k6538ec61e1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__kd41b3b8ad7__k6538ec61e1" eSuperTypes="//Tag__Role__Import__kd41b3b8ad7 //Role__k6538ec61e1">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关系始端 [ k6538ec61e1 ] "/>
      <details key="parent" value="kd41b3b8ad7"/>
      <details key="self" value="k6538ec61e1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__k6538ec61e1" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关系始端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__k6538ec61e1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__kf2004d8ed5" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__kf2004d8ed5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__kd41b3b8ad7__kf2004d8ed5" eSuperTypes="//Tag__Role__Export__kd41b3b8ad7 //Role__kf2004d8ed5">
    <eAnnotations source="annotation">
      <details key="shape" value="arrowShape"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关系终端 [ kf2004d8ed5 ] "/>
      <details key="parent" value="kd41b3b8ad7"/>
      <details key="self" value="kf2004d8ed5"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__kf2004d8ed5" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关系终端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__kf2004d8ed5" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k8b3baa8fa9__kd41b3b8ad7" eSuperTypes="//Tag__Relationship__k8b3baa8fa9 //Relationship__kd41b3b8ad7">
    <eAnnotations source="annotation">
      <details key="parent" value="k8b3baa8fa9"/>
      <details key="self" value="kd41b3b8ad7"/>
      <details key="roles" value="k6538ec61e1,kf2004d8ed5"/>
      <details key="metaInfo" value="具备 [ kd41b3b8ad7 ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
