<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="k9c1d649899" nsURI="D:/Office/MetaGraph20241130_208zjs/ArchModeling/workspace/城市智慧管理-体系V1.0/语言/体系/图元模型/k9c1d649899.karma"
    nsPrefix="k9c1d649899">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuiltIn" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KLayout">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KMatrix">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPlugin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KGraph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRelationship">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPointGen" eSuperTypes="#//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPointGen" eSuperTypes="#//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedPointGen" eSuperTypes="#//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportRoleGen" eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportRoleGen" eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTable"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableRow"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellGen" eSuperTypes="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableCell"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model__k9c1d649899" eSuperTypes="#//GraphGen">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="活动推出能力 [ k9c1d649899 ] "/>
      <details key="self" value="k9c1d649899"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="活动推出能力"/>
    </eAnnotations>
    <eAnnotations source="Binding">
      <details key="sourceRule" value="Def__k9c1d649899__ka8cc7e18cc->Def__k6d6bb252d0__k6538ec61e1,Def__k9c1d649899__kcaa9788539->Def__k6d6bb252d0__k6538ec61e1"/>
      <details key="targetRule" value="Def__k9c1d649899__kcaa9788539->Def__k6d6bb252d0__kf2004d8ed5"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1"
        eType="#//Tag__Layout__k9c1d649899" containment="true" eOpposite="#//Tag__Layout__k9c1d649899/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Tag__Table__k9c1d649899" containment="true" eOpposite="#//Tag__Table__k9c1d649899/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrixs" upperBound="-1"
        eType="#//Tag__Matrix__k9c1d649899" containment="true" eOpposite="#//Tag__Matrix__k9c1d649899/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gantts" upperBound="-1"
        eType="#//Gantt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__k9c1d649899" containment="true" eOpposite="#//Tag__Property__k9c1d649899/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//Tag__Object__k9c1d649899" containment="true" eOpposite="#//Tag__Object__k9c1d649899/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1"
        eType="#//Tag__Relationship__k9c1d649899" containment="true" eOpposite="#//Tag__Relationship__k9c1d649899/enclosingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Layout__k9c1d649899" eSuperTypes="#//LayoutGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramKind" eType="#//diagramKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementType" eType="#//modelElementTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k9c1d649899" eOpposite="#//Model__k9c1d649899/layouts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagramKinds">
    <eLiterals name="bdd"/>
    <eLiterals name="idd" value="1"/>
    <eLiterals name="uc" value="2"/>
    <eLiterals name="act" value="3"/>
    <eLiterals name="sd" value="4"/>
    <eLiterals name="stm" value="5"/>
    <eLiterals name="par" value="6"/>
    <eLiterals name="req" value="7"/>
    <eLiterals name="pkg" value="8"/>
    <eLiterals name="annotation" value="9"/>
    <eLiterals name="others" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="modelElementTypes">
    <eLiterals name="package"/>
    <eLiterals name="model" value="1"/>
    <eLiterals name="modelLibrary" value="2"/>
    <eLiterals name="view" value="3"/>
    <eLiterals name="block" value="4"/>
    <eLiterals name="constraintBlock" value="5"/>
    <eLiterals name="activity" value="6"/>
    <eLiterals name="interaction" value="7"/>
    <eLiterals name="stateMachine" value="8"/>
    <eLiterals name="profile" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__layout" eSuperTypes="#//Tag__Layout__k9c1d649899 #//LayoutGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="布局插件"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Table__k9c1d649899" eSuperTypes="#//TableGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k9c1d649899" eOpposite="#//Model__k9c1d649899/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__table" eSuperTypes="#//Tag__Table__k9c1d649899 #//TableGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Matrix__k9c1d649899" eSuperTypes="#//MatrixGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k9c1d649899" eOpposite="#//Model__k9c1d649899/matrixs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__matrix" eSuperTypes="#//Tag__Matrix__k9c1d649899 #//MatrixGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gantt" eSuperTypes="#//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="#//times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTasks" upperBound="-1"
        eType="#//GanttTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="times">
    <eLiterals name="YEAR"/>
    <eLiterals name="MONTH" value="1"/>
    <eLiterals name="DAY" value="2"/>
    <eLiterals name="HOUR" value="3"/>
    <eLiterals name="MINUTE" value="4"/>
    <eLiterals name="SECOND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__gantt" eSuperTypes="#//Gantt"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTask" abstract="true" eSuperTypes="#//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTaskElements" upperBound="-1"
        eType="#//GanttTaskElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__ganttTask" eSuperTypes="#//GanttTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTaskElement" abstract="true" eSuperTypes="#//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementOffset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__ganttTaskElement"
      eSuperTypes="#//GanttTaskElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k9c1d649899" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k9c1d649899" eOpposite="#//Model__k9c1d649899/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Object__k9c1d649899" abstract="true"
      eSuperTypes="#//ObjectGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k9c1d649899" eOpposite="#//Model__k9c1d649899/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Relationship__k9c1d649899" abstract="true"
      eSuperTypes="#//RelationshipGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false"
        lowerBound="1" eType="#//Model__k9c1d649899" eOpposite="#//Model__k9c1d649899/relationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__BUILTIN_Object_Transfer_ka8cc7e18cc"
      abstract="true" eSuperTypes="#//ObjectGen #//BuiltIn">
    <eAnnotations source="LocalLabel">
      <details key="name" value="活动动作"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__BUILTIN_Object_Transfer_ka8cc7e18cc" containment="true"
        eOpposite="#//Tag__Property__BUILTIN_Object_Transfer_ka8cc7e18cc/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Tag__InputPoint__BUILTIN_Object_Transfer_ka8cc7e18cc" containment="true"
        eOpposite="#//Tag__InputPoint__BUILTIN_Object_Transfer_ka8cc7e18cc/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Tag__OutputPoint__BUILTIN_Object_Transfer_ka8cc7e18cc" containment="true"
        eOpposite="#//Tag__OutputPoint__BUILTIN_Object_Transfer_ka8cc7e18cc/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1"
        eType="#//Tag__UndirectedPoint__BUILTIN_Object_Transfer_ka8cc7e18cc" containment="true"
        eOpposite="#//Tag__UndirectedPoint__BUILTIN_Object_Transfer_ka8cc7e18cc/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__BUILTIN_Object_Transfer_ka8cc7e18cc"
      abstract="true" eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc" eOpposite="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__BUILTIN_Object_Transfer_ka8cc7e18cc"
      abstract="true" eSuperTypes="#//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc" eOpposite="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__BUILTIN_Object_Transfer_ka8cc7e18cc"
      abstract="true" eSuperTypes="#//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc" eOpposite="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__BUILTIN_Object_Transfer_ka8cc7e18cc"
      abstract="true" eSuperTypes="#//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc" eOpposite="#//Object__BUILTIN_Object_Transfer_ka8cc7e18cc/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__ka8cc7e18cc" abstract="true"
      eSuperTypes="#//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="活动动作"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__ka8cc7e18cc" containment="true" eOpposite="#//Tag__Property__ka8cc7e18cc/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Tag__InputPoint__ka8cc7e18cc" containment="true" eOpposite="#//Tag__InputPoint__ka8cc7e18cc/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Tag__OutputPoint__ka8cc7e18cc" containment="true" eOpposite="#//Tag__OutputPoint__ka8cc7e18cc/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1"
        eType="#//Tag__UndirectedPoint__ka8cc7e18cc" containment="true" eOpposite="#//Tag__UndirectedPoint__ka8cc7e18cc/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__ka8cc7e18cc" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__ka8cc7e18cc" eOpposite="#//Object__ka8cc7e18cc/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__ka8cc7e18cc" abstract="true"
      eSuperTypes="#//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__ka8cc7e18cc" eOpposite="#//Object__ka8cc7e18cc/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__ka8cc7e18cc" abstract="true"
      eSuperTypes="#//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__ka8cc7e18cc" eOpposite="#//Object__ka8cc7e18cc/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__ka8cc7e18cc" abstract="true"
      eSuperTypes="#//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__ka8cc7e18cc" eOpposite="#//Object__ka8cc7e18cc/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__ka8cc7e18cc_kb10cf08e6a_5d4e9e"
      abstract="true" eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingPoint" ordered="false"
        lowerBound="1" eType="#//Point__ka8cc7e18cc_kb10cf08e6a_5d4e9e" eOpposite="#//Point__ka8cc7e18cc_kb10cf08e6a_5d4e9e/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point__ka8cc7e18cc_kb10cf08e6a_5d4e9e"
      eSuperTypes="#//InputPointGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输入"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__ka8cc7e18cc_kb10cf08e6a_5d4e9e" containment="true"
        eOpposite="#//Tag__Property__ka8cc7e18cc_kb10cf08e6a_5d4e9e/enclosingPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__ka8cc7e18cc__ka8cc7e18cc_kb10cf08e6a_5d4e9e"
      eSuperTypes="#//Tag__InputPoint__ka8cc7e18cc #//Point__ka8cc7e18cc_kb10cf08e6a_5d4e9e">
    <eAnnotations source="annotation">
      <details key="pointShape" value="triangle"/>
      <details key="parent" value="ka8cc7e18cc"/>
      <details key="self" value="ka8cc7e18cc_kb10cf08e6a_5d4e9e"/>
      <details key="metaInfo" value="通信中继输入 [ ka8cc7e18cc_kb10cf08e6a_5d4e9e ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输入"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__ka8cc7e18cc_kb76db55211_44fe51"
      abstract="true" eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingPoint" ordered="false"
        lowerBound="1" eType="#//Point__ka8cc7e18cc_kb76db55211_44fe51" eOpposite="#//Point__ka8cc7e18cc_kb76db55211_44fe51/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point__ka8cc7e18cc_kb76db55211_44fe51"
      eSuperTypes="#//OutputPointGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输出"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__ka8cc7e18cc_kb76db55211_44fe51" containment="true"
        eOpposite="#//Tag__Property__ka8cc7e18cc_kb76db55211_44fe51/enclosingPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__ka8cc7e18cc__ka8cc7e18cc_kb76db55211_44fe51"
      eSuperTypes="#//Tag__OutputPoint__ka8cc7e18cc #//Point__ka8cc7e18cc_kb76db55211_44fe51">
    <eAnnotations source="annotation">
      <details key="pointShape" value="triangle"/>
      <details key="parent" value="ka8cc7e18cc"/>
      <details key="self" value="ka8cc7e18cc_kb76db55211_44fe51"/>
      <details key="metaInfo" value="通信中继输出 [ ka8cc7e18cc_kb76db55211_44fe51 ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="通信中继输出"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__kcaa9788539" abstract="true"
      eSuperTypes="#//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="所需能力"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__kcaa9788539" containment="true" eOpposite="#//Tag__Property__kcaa9788539/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Tag__InputPoint__kcaa9788539" containment="true" eOpposite="#//Tag__InputPoint__kcaa9788539/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Tag__OutputPoint__kcaa9788539" containment="true" eOpposite="#//Tag__OutputPoint__kcaa9788539/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1"
        eType="#//Tag__UndirectedPoint__kcaa9788539" containment="true" eOpposite="#//Tag__UndirectedPoint__kcaa9788539/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__kcaa9788539" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__kcaa9788539" eOpposite="#//Object__kcaa9788539/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__kcaa9788539" abstract="true"
      eSuperTypes="#//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__kcaa9788539" eOpposite="#//Object__kcaa9788539/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__kcaa9788539" abstract="true"
      eSuperTypes="#//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__kcaa9788539" eOpposite="#//Object__kcaa9788539/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__kcaa9788539" abstract="true"
      eSuperTypes="#//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false"
        lowerBound="1" eType="#//Object__kcaa9788539" eOpposite="#//Object__kcaa9788539/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__BUILTIN_Object_Transfer_ka8cc7e18cc"
      eSuperTypes="#//Tag__Object__k9c1d649899 #//Object__BUILTIN_Object_Transfer_ka8cc7e18cc">
    <eAnnotations source="annotation">
      <details key="self" value="BUILTIN_Object_Transfer_ka8cc7e18cc"/>
      <details key="parent" value="k9c1d649899"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="活动动作[BUILTIN_Object_Transfer_ka8cc7e18cc]"/>
      <details key="properties" value=""/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
      <details key="referedMetaObject" value="ka8cc7e18cc"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="活动动作"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="#//Def__k9c1d649899__BUILTIN_Object_Transfer_ka8cc7e18cc__decomposeN"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1"
        eType="#//Def__k9c1d649899__BUILTIN_Object_Transfer_ka8cc7e18cc__explodesN"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__BUILTIN_Object_Transfer_ka8cc7e18cc__decomposeN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__BUILTIN_Object_Transfer_ka8cc7e18cc__explodesN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__ka8cc7e18cc" eSuperTypes="#//Tag__Object__k9c1d649899 #//Object__ka8cc7e18cc">
    <eAnnotations source="annotation">
      <details key="self" value="ka8cc7e18cc"/>
      <details key="parent" value="k9c1d649899"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="roundedRectangle"/>
      <details key="metaInfo" value="活动动作[ka8cc7e18cc]"/>
      <details key="properties" value=""/>
      <details key="input" value="Def__ka8cc7e18cc__ka8cc7e18cc_kb10cf08e6a_5d4e9e,ka8cc7e18cc_kb10cf08e6a_5d4e9e,通信中继输入"/>
      <details key="output" value="Def__ka8cc7e18cc__ka8cc7e18cc_kb76db55211_44fe51,ka8cc7e18cc_kb76db55211_44fe51,通信中继输出"/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="活动动作"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="#//Def__k9c1d649899__ka8cc7e18cc__decomposeN"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1"
        eType="#//Def__k9c1d649899__ka8cc7e18cc__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__ka8cc7e18cc__decomposeN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__ka8cc7e18cc__explodesN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__kcaa9788539" eSuperTypes="#//Tag__Object__k9c1d649899 #//Object__kcaa9788539">
    <eAnnotations source="annotation">
      <details key="self" value="kcaa9788539"/>
      <details key="parent" value="k9c1d649899"/>
      <details key="mode" value="blankPropertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="所需能力[kcaa9788539]"/>
      <details key="properties" value=""/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="所需能力"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="#//Def__k9c1d649899__kcaa9788539__decomposeN"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1"
        eType="#//Def__k9c1d649899__kcaa9788539__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__kcaa9788539__decomposeN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__kcaa9788539__explodesN"
      eSuperTypes="#//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k6d6bb252d0" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship"
        ordered="false" lowerBound="1" eType="#//Relationship__k6d6bb252d0" eOpposite="#//Relationship__k6d6bb252d0/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__k6d6bb252d0" eSuperTypes="#//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="对应"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__k6d6bb252d0" containment="true" eOpposite="#//Tag__Property__k6d6bb252d0/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="#//Tag__Role__Import__k6d6bb252d0"
        containment="true" eOpposite="#//Tag__Role__Import__k6d6bb252d0/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="#//Tag__Role__Export__k6d6bb252d0"
        containment="true" eOpposite="#//Tag__Role__Export__k6d6bb252d0/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__k6d6bb252d0" abstract="true"
      eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship"
        ordered="false" lowerBound="1" eType="#//Relationship__k6d6bb252d0" eOpposite="#//Relationship__k6d6bb252d0/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__k6d6bb252d0" abstract="true"
      eSuperTypes="#//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship"
        ordered="false" lowerBound="1" eType="#//Relationship__k6d6bb252d0" eOpposite="#//Relationship__k6d6bb252d0/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__k6538ec61e1" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false"
        lowerBound="1" eType="#//Role__k6538ec61e1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k6d6bb252d0__k6538ec61e1" eSuperTypes="#//Tag__Role__Import__k6d6bb252d0 #//Role__k6538ec61e1">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关系始端 [ k6538ec61e1 ] "/>
      <details key="parent" value="k6d6bb252d0"/>
      <details key="self" value="k6538ec61e1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__k6538ec61e1" eSuperTypes="#//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关系始端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__k6538ec61e1" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__kf2004d8ed5" abstract="true"
      eSuperTypes="#//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false"
        lowerBound="1" eType="#//Role__kf2004d8ed5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k6d6bb252d0__kf2004d8ed5" eSuperTypes="#//Tag__Role__Export__k6d6bb252d0 #//Role__kf2004d8ed5">
    <eAnnotations source="annotation">
      <details key="shape" value="arrowShape"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="关系终端 [ kf2004d8ed5 ] "/>
      <details key="parent" value="k6d6bb252d0"/>
      <details key="self" value="kf2004d8ed5"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__kf2004d8ed5" eSuperTypes="#//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="关系终端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Tag__Property__kf2004d8ed5" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__k9c1d649899__k6d6bb252d0" eSuperTypes="#//Tag__Relationship__k9c1d649899 #//Relationship__k6d6bb252d0">
    <eAnnotations source="annotation">
      <details key="parent" value="k9c1d649899"/>
      <details key="self" value="k6d6bb252d0"/>
      <details key="roles" value="k6538ec61e1,kf2004d8ed5"/>
      <details key="metaInfo" value="对应 [ k6d6bb252d0 ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="k7bd7f33a01_object_69e1" instanceTypeName="kcaa9788539"/>
  <eClassifiers xsi:type="ecore:EClass" name="k7bd7f33a01_object_a572" instanceTypeName="kcaa9788539"/>
  <eClassifiers xsi:type="ecore:EClass" name="k7bd7f33a01_object_983c" instanceTypeName="kcaa9788539"/>
  <eClassifiers xsi:type="ecore:EClass" name="k7bd7f33a01_object_1c5e" instanceTypeName="kcaa9788539"/>
  <eClassifiers xsi:type="ecore:EClass" name="k7bd7f33a01_object_65b3" instanceTypeName="kcaa9788539"/>
  <eClassifiers xsi:type="ecore:EClass" name="k7bd7f33a01_object_c083" instanceTypeName="kcaa9788539"/>
  <eClassifiers xsi:type="ecore:EClass" name="k7bd7f33a01_object_145a" instanceTypeName="kcaa9788539"/>
</ecore:EPackage>
