<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Diagram_Requirement" nsURI="D:/MetaGraph_2/MetaGraph/workspace/LGS_V6/语言/LGS/图元模型/Diagram_Requirement.karma" nsPrefix="Diagram_Requirement">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KLayout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KMatrix"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPlugin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model__Diagram_Requirement" eSuperTypes="//GraphGen">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="Requirement Diagram [ Diagram_Requirement ] "/>
      <details key="self" value="Diagram_Requirement"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="Requirement Diagram"/>
    </eAnnotations>
    <eAnnotations source="Binding">
      <details key="sourceRule" value="Def__Diagram_Requirement__Object_Requirement->Def__Relationship_Containment__Role_Containment_Source,Def__Diagram_Requirement__Object_Requirement->Def__Relationship_Refine__Role_Refine_Source"/>
      <details key="targetRule" value="Def__Diagram_Requirement__Object_Requirement->Def__Relationship_Containment__Role_Containment_Target,Def__Diagram_Requirement__Object_Requirement->Def__Relationship_Refine__Role_Refine_Target"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1" eType="//Tag__Layout__Diagram_Requirement" containment="true" eOpposite="//Tag__Layout__Diagram_Requirement/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1" eType="//Tag__Table__Diagram_Requirement" containment="true" eOpposite="//Tag__Table__Diagram_Requirement/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrixs" upperBound="-1" eType="//Tag__Matrix__Diagram_Requirement" containment="true" eOpposite="//Tag__Matrix__Diagram_Requirement/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gantts" upperBound="-1" eType="//Gantt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Diagram_Requirement" containment="true" eOpposite="//Tag__Property__Diagram_Requirement/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1" eType="//Tag__Object__Diagram_Requirement" containment="true" eOpposite="//Tag__Object__Diagram_Requirement/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1" eType="//Tag__Relationship__Diagram_Requirement" containment="true" eOpposite="//Tag__Relationship__Diagram_Requirement/enclosingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Layout__Diagram_Requirement" eSuperTypes="//LayoutGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramKind" eType="//diagramKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementType" eType="//modelElementTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Diagram_Requirement" eOpposite="//Model__Diagram_Requirement/layouts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagramKinds">
    <eLiterals name="bdd"/>
    <eLiterals name="idd" value="1"/>
    <eLiterals name="uc" value="2"/>
    <eLiterals name="act" value="3"/>
    <eLiterals name="sd" value="4"/>
    <eLiterals name="stm" value="5"/>
    <eLiterals name="par" value="6"/>
    <eLiterals name="req" value="7"/>
    <eLiterals name="pkg" value="8"/>
    <eLiterals name="annotation" value="9"/>
    <eLiterals name="others" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="modelElementTypes">
    <eLiterals name="package"/>
    <eLiterals name="model" value="1"/>
    <eLiterals name="modelLibrary" value="2"/>
    <eLiterals name="view" value="3"/>
    <eLiterals name="block" value="4"/>
    <eLiterals name="constraintBlock" value="5"/>
    <eLiterals name="activity" value="6"/>
    <eLiterals name="interaction" value="7"/>
    <eLiterals name="stateMachine" value="8"/>
    <eLiterals name="profile" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__layout" eSuperTypes="//Tag__Layout__Diagram_Requirement //LayoutGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="布局插件"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Table__Diagram_Requirement" eSuperTypes="//TableGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Diagram_Requirement" eOpposite="//Model__Diagram_Requirement/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__table" eSuperTypes="//Tag__Table__Diagram_Requirement //TableGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Matrix__Diagram_Requirement" eSuperTypes="//MatrixGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Diagram_Requirement" eOpposite="//Model__Diagram_Requirement/matrixs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__matrix" eSuperTypes="//Tag__Matrix__Diagram_Requirement //MatrixGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gantt" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="//times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTasks" upperBound="-1" eType="//GanttTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="times">
    <eLiterals name="YEAR"/>
    <eLiterals name="MONTH" value="1"/>
    <eLiterals name="DAY" value="2"/>
    <eLiterals name="HOUR" value="3"/>
    <eLiterals name="MINUTE" value="4"/>
    <eLiterals name="SECOND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__gantt" eSuperTypes="//Gantt"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTask" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTaskElements" upperBound="-1" eType="//GanttTaskElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__ganttTask" eSuperTypes="//GanttTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTaskElement" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementOffset">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementLength">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementColor">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__ganttTaskElement" eSuperTypes="//GanttTaskElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Diagram_Requirement" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Diagram_Requirement" eOpposite="//Model__Diagram_Requirement/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Object__Diagram_Requirement" abstract="true" eSuperTypes="//ObjectGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Diagram_Requirement" eOpposite="//Model__Diagram_Requirement/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Relationship__Diagram_Requirement" abstract="true" eSuperTypes="//RelationshipGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Diagram_Requirement" eOpposite="//Model__Diagram_Requirement/relationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__Object_Requirement" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Requirement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Object_Requirement" containment="true" eOpposite="//Tag__Property__Object_Requirement/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__Object_Requirement" containment="true" eOpposite="//Tag__InputPoint__Object_Requirement/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__Object_Requirement" containment="true" eOpposite="//Tag__OutputPoint__Object_Requirement/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__Object_Requirement" containment="true" eOpposite="//Tag__UndirectedPoint__Object_Requirement/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Object_Requirement" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Requirement" eOpposite="//Object__Object_Requirement/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__Object_Requirement" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Requirement" eOpposite="//Object__Object_Requirement/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__Object_Requirement" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Requirement" eOpposite="//Object__Object_Requirement/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__Object_Requirement" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Requirement" eOpposite="//Object__Object_Requirement/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_Name" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Name"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Object_Requirement__Object_Requirement_Property_Name_29d355" eSuperTypes="//Property__Property_Name //Tag__Property__Object_Requirement">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="Name [ Object_Requirement_Property_Name_29d355 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="Name"/>
      <details key="value" value="null"/>
      <details key="self" value="Object_Requirement_Property_Name_29d355"/>
      <details key="parent" value="Object_Requirement"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="Name"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_ID" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="ID"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Object_Requirement__Object_Requirement_Property_ID_b6d53b" eSuperTypes="//Property__Property_ID //Tag__Property__Object_Requirement">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="ID [ Object_Requirement_Property_ID_b6d53b ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="ID"/>
      <details key="value" value="null"/>
      <details key="self" value="Object_Requirement_Property_ID_b6d53b"/>
      <details key="parent" value="Object_Requirement"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="ID"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_Text" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Text"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Object_Requirement__Object_Requirement_Property_Text_2c7b97" eSuperTypes="//Property__Property_Text //Tag__Property__Object_Requirement">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="Text [ Object_Requirement_Property_Text_2c7b97 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="Text"/>
      <details key="value" value="null"/>
      <details key="self" value="Object_Requirement_Property_Text_2c7b97"/>
      <details key="parent" value="Object_Requirement"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="Text"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__Object_Requirement" eSuperTypes="//Tag__Object__Diagram_Requirement //Object__Object_Requirement">
    <eAnnotations source="annotation">
      <details key="self" value="Object_Requirement"/>
      <details key="parent" value="Diagram_Requirement"/>
      <details key="mode" value="propertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="LocalLabel" value="Requirement"/>
      <details key="metaInfo" value="Requirement[Object_Requirement]"/>
      <details key="properties" value="Def__Object_Requirement__Object_Requirement_Property_Name_29d355,Object_Requirement_Property_Name_29d355,Name,null;Def__Object_Requirement__Object_Requirement_Property_ID_b6d53b,Object_Requirement_Property_ID_b6d53b,ID,null;Def__Object_Requirement__Object_Requirement_Property_Text_2c7b97,Object_Requirement_Property_Text_2c7b97,Text,null"/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="Requirement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__Diagram_Requirement__Object_Requirement__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__Diagram_Requirement__Object_Requirement__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__Object_Requirement__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__Object_Requirement__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Relationship_Containment" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Containment" eOpposite="//Relationship__Relationship_Containment/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__Relationship_Containment" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Containment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Relationship_Containment" containment="true" eOpposite="//Tag__Property__Relationship_Containment/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__Relationship_Containment" containment="true" eOpposite="//Tag__Role__Import__Relationship_Containment/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__Relationship_Containment" containment="true" eOpposite="//Tag__Role__Export__Relationship_Containment/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__Relationship_Containment" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Containment" eOpposite="//Relationship__Relationship_Containment/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__Relationship_Containment" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Containment" eOpposite="//Relationship__Relationship_Containment/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Role_Containment_Source" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Role_Containment_Source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Relationship_Containment__Role_Containment_Source" eSuperTypes="//Tag__Role__Import__Relationship_Containment //Role__Role_Containment_Source">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="Containment_Source [ Role_Containment_Source ] "/>
      <details key="LocalLabel" value="Containment_Source"/>
      <details key="parent" value="Relationship_Containment"/>
      <details key="self" value="Role_Containment_Source"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Role_Containment_Source" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Containment_Source"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Role_Containment_Source" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Role_Containment_Target" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Role_Containment_Target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Relationship_Containment__Role_Containment_Target" eSuperTypes="//Tag__Role__Export__Relationship_Containment //Role__Role_Containment_Target">
    <eAnnotations source="annotation">
      <details key="shape" value="ring"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="Containment_Target [ Role_Containment_Target ] "/>
      <details key="LocalLabel" value="Containment_Target"/>
      <details key="parent" value="Relationship_Containment"/>
      <details key="self" value="Role_Containment_Target"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Role_Containment_Target" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Containment_Target"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Role_Containment_Target" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__Relationship_Containment" eSuperTypes="//Tag__Relationship__Diagram_Requirement //Relationship__Relationship_Containment">
    <eAnnotations source="annotation">
      <details key="parent" value="Diagram_Requirement"/>
      <details key="self" value="Relationship_Containment"/>
      <details key="roles" value="Role_Containment_Source,Role_Containment_Target"/>
      <details key="metaInfo" value="Containment [ Relationship_Containment ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Relationship_Refine" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Refine" eOpposite="//Relationship__Relationship_Refine/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__Relationship_Refine" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Refine"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Relationship_Refine" containment="true" eOpposite="//Tag__Property__Relationship_Refine/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__Relationship_Refine" containment="true" eOpposite="//Tag__Role__Import__Relationship_Refine/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__Relationship_Refine" containment="true" eOpposite="//Tag__Role__Export__Relationship_Refine/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__Relationship_Refine" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Refine" eOpposite="//Relationship__Relationship_Refine/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__Relationship_Refine" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Refine" eOpposite="//Relationship__Relationship_Refine/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Role_Refine_Source" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Role_Refine_Source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Relationship_Refine__Role_Refine_Source" eSuperTypes="//Tag__Role__Import__Relationship_Refine //Role__Role_Refine_Source">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="Refine_Source [ Role_Refine_Source ] "/>
      <details key="LocalLabel" value="Refine_Source"/>
      <details key="parent" value="Relationship_Refine"/>
      <details key="self" value="Role_Refine_Source"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Role_Refine_Source" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Refine_Source"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Role_Refine_Source" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Role_Refine_Target" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Role_Refine_Target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Relationship_Refine__Role_Refine_Target" eSuperTypes="//Tag__Role__Export__Relationship_Refine //Role__Role_Refine_Target">
    <eAnnotations source="annotation">
      <details key="shape" value="arrowShape"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="Refine_Target [ Role_Refine_Target ] "/>
      <details key="LocalLabel" value="Refine_Target"/>
      <details key="parent" value="Relationship_Refine"/>
      <details key="self" value="Role_Refine_Target"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Role_Refine_Target" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="Refine_Target"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Role_Refine_Target" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Diagram_Requirement__Relationship_Refine" eSuperTypes="//Tag__Relationship__Diagram_Requirement //Relationship__Relationship_Refine">
    <eAnnotations source="annotation">
      <details key="parent" value="Diagram_Requirement"/>
      <details key="self" value="Relationship_Refine"/>
      <details key="roles" value="Role_Refine_Source,Role_Refine_Target"/>
      <details key="metaInfo" value="Refine [ Relationship_Refine ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
