<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Sequence_Diagram" nsURI="D:/Software/eclipse-rcp-2020-03-R-win32-x86_642/eclipse/WorkSpace208/tool208mcif/runtime-MetaGraph3/仿真案例测试/语言/SysML/图元模型/Sequence_Diagram.karma" nsPrefix="Sequence_Diagram">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//Diagram"/>
    <eSuperTypes href="/仿真案例测试/语言/SysML/图元模型/Sequence_Diagram.ecore#//Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KLayout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MatrixGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KMatrix"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GanttGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPlugin"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GraphGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KGraph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PointGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KPoint"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refValue">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UndirectedPointGen" eSuperTypes="//PointGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImportRoleGen" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRowGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableRow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCellGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//KTableCell"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionGen">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//ValueSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bodies" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="langues" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//AbstractConstraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceRole">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceMessage">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind">
      <eType xsi:type="ecore:EEnum" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//MessageKind"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangeContext" eType="//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendingEnd" eType="//MessageEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivingEnd" eType="//MessageEnd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="AsyncMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="SyncMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReplyMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="DestructMessage" eSuperTypes="//SequenceMessage"/>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionFragment" abstract="true">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coveredInstanceRoles" lowerBound="1" upperBound="-1" eType="//InstanceRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionState" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//StateFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FragmentEnd" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//AbstractFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedInteractionFragments" upperBound="-1" eType="//InteractionFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEnd" abstract="true" eSuperTypes="//InteractionFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EClass" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageEnd" eSuperTypes="//AbstractEnd">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//SequenceMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEnd" eSuperTypes="//AbstractEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" ordered="false" lowerBound="1" eType="//Execution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gate" eSuperTypes="//MessageEnd"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeLapse" abstract="true">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" ordered="false" lowerBound="1" eType="//InteractionFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finish" ordered="false" lowerBound="1" eType="//InteractionFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFragment" abstract="true" eSuperTypes="//TimeLapse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedGates" upperBound="-1" eType="//Gate" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionUse" eSuperTypes="//AbstractFragment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedScenario" eType="//Scenario" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" eSuperTypes="//AbstractFragment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" defaultValueLiteral="UNSET">
      <eType xsi:type="ecore:EEnum" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//InteractionOperatorKind"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedOperands" upperBound="-1" eType="//InteractionOperand"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Execution" eSuperTypes="//TimeLapse">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateFragment" eSuperTypes="//TimeLapse"/>
  <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventReceiptOperation" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventSentOperation" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreationEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="DestructionEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArmTimerEvent" eSuperTypes="//Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConstraintDuratio">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" eType="//InteractionFragment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finish" eType="//InteractionFragment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eSuperTypes href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaMetaType">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" defaultValueLiteral="UNSET">
      <eType xsi:type="ecore:EEnum" href="platform:/plugin/org.fc.mdt.ecore/model/karma.ecore#//ScenarioKind"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstanceRoles" upperBound="-1" eType="//InstanceRole" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMessages" upperBound="-1" eType="//SequenceMessage" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInteractionFragments" upperBound="-1" eType="//InteractionFragment" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTimeLapses" upperBound="-1" eType="//TimeLapse" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEvents" upperBound="-1" eType="//Event" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConstraintDurations" upperBound="-1" eType="//ConstraintDuratio" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preCondition" eType="//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postCondition" eType="//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model__Sequence_Diagram" eSuperTypes="//GraphGen">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="时序图 [ Sequence_Diagram ] "/>
      <details key="self" value="Sequence_Diagram"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="时序图"/>
    </eAnnotations>
    <eAnnotations source="Binding">
      <details key="sourceRule" value="Def__Sequence_Diagram__Object_Lifeline->Def__Relationship_Event__Relationship_Event_End"/>
      <details key="targetRule" value="Def__Sequence_Diagram__Object_Lifeline->Def__Relationship_Event__Relationship_Event_Start"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layouts" upperBound="-1" eType="//Tag__Layout__Sequence_Diagram" containment="true" eOpposite="//Tag__Layout__Sequence_Diagram/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1" eType="//Tag__Table__Sequence_Diagram" containment="true" eOpposite="//Tag__Table__Sequence_Diagram/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matrixs" upperBound="-1" eType="//Tag__Matrix__Sequence_Diagram" containment="true" eOpposite="//Tag__Matrix__Sequence_Diagram/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gantts" upperBound="-1" eType="//Gantt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Sequence_Diagram" containment="true" eOpposite="//Tag__Property__Sequence_Diagram/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1" eType="//Tag__Object__Sequence_Diagram" containment="true" eOpposite="//Tag__Object__Sequence_Diagram/enclosingGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationships" upperBound="-1" eType="//Tag__Relationship__Sequence_Diagram" containment="true" eOpposite="//Tag__Relationship__Sequence_Diagram/enclosingGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Layout__Sequence_Diagram" eSuperTypes="//LayoutGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagramKind" eType="//diagramKinds"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementType" eType="//modelElementTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelElementName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Sequence_Diagram" eOpposite="//Model__Sequence_Diagram/layouts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagramKinds">
    <eLiterals name="bdd"/>
    <eLiterals name="idd" value="1"/>
    <eLiterals name="uc" value="2"/>
    <eLiterals name="act" value="3"/>
    <eLiterals name="sd" value="4"/>
    <eLiterals name="stm" value="5"/>
    <eLiterals name="par" value="6"/>
    <eLiterals name="req" value="7"/>
    <eLiterals name="pkg" value="8"/>
    <eLiterals name="annotation" value="9"/>
    <eLiterals name="others" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="modelElementTypes">
    <eLiterals name="package"/>
    <eLiterals name="model" value="1"/>
    <eLiterals name="modelLibrary" value="2"/>
    <eLiterals name="view" value="3"/>
    <eLiterals name="block" value="4"/>
    <eLiterals name="constraintBlock" value="5"/>
    <eLiterals name="activity" value="6"/>
    <eLiterals name="interaction" value="7"/>
    <eLiterals name="stateMachine" value="8"/>
    <eLiterals name="profile" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__layout" eSuperTypes="//Tag__Layout__Sequence_Diagram //LayoutGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="布局插件"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Table__Sequence_Diagram" eSuperTypes="//TableGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Sequence_Diagram" eOpposite="//Model__Sequence_Diagram/tables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__table" eSuperTypes="//Tag__Table__Sequence_Diagram //TableGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Matrix__Sequence_Diagram" eSuperTypes="//MatrixGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Sequence_Diagram" eOpposite="//Model__Sequence_Diagram/matrixs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__matrix" eSuperTypes="//Tag__Matrix__Sequence_Diagram //MatrixGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="表单"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gantt" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="//times"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeUnit">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTasks" upperBound="-1" eType="//GanttTask" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="times">
    <eLiterals name="YEAR"/>
    <eLiterals name="MONTH" value="1"/>
    <eLiterals name="DAY" value="2"/>
    <eLiterals name="HOUR" value="3"/>
    <eLiterals name="MINUTE" value="4"/>
    <eLiterals name="SECOND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__gantt" eSuperTypes="//Gantt"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTask" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ganttTaskElements" upperBound="-1" eType="//GanttTaskElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__ganttTask" eSuperTypes="//GanttTask"/>
  <eClassifiers xsi:type="ecore:EClass" name="GanttTaskElement" abstract="true" eSuperTypes="//GanttGen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementOffset">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementLength">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementColor">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__ganttTaskElement" eSuperTypes="//GanttTaskElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Sequence_Diagram" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Sequence_Diagram" eOpposite="//Model__Sequence_Diagram/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Object__Sequence_Diagram" abstract="true" eSuperTypes="//ObjectGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Sequence_Diagram" eOpposite="//Model__Sequence_Diagram/objects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Relationship__Sequence_Diagram" abstract="true" eSuperTypes="//RelationshipGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingGraph" ordered="false" lowerBound="1" eType="//Model__Sequence_Diagram" eOpposite="//Model__Sequence_Diagram/relationships"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_To_Do" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="待办事项"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__Sequence_Diagram_Property_To_Do_566541" eSuperTypes="//Tag__Property__Sequence_Diagram //Property__Property_To_Do">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="待办事项 [ Sequence_Diagram_Property_To_Do_566541 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="待办事项"/>
      <details key="value" value="null"/>
      <details key="self" value="Sequence_Diagram_Property_To_Do_566541"/>
      <details key="parent" value="Sequence_Diagram"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="待办事项"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="待办事项"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_Context" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="上下文"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__Sequence_Diagram_Property_Context_eb3d1b" eSuperTypes="//Tag__Property__Sequence_Diagram //Property__Property_Context">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="上下文 [ Sequence_Diagram_Property_Context_eb3d1b ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="上下文"/>
      <details key="value" value="null"/>
      <details key="self" value="Sequence_Diagram_Property_Context_eb3d1b"/>
      <details key="parent" value="Sequence_Diagram"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="上下文"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="上下文"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Object__Object_Lifeline" abstract="true" eSuperTypes="//ObjectGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="生命线"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Object_Lifeline" containment="true" eOpposite="//Tag__Property__Object_Lifeline/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1" eType="//Tag__InputPoint__Object_Lifeline" containment="true" eOpposite="//Tag__InputPoint__Object_Lifeline/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1" eType="//Tag__OutputPoint__Object_Lifeline" containment="true" eOpposite="//Tag__OutputPoint__Object_Lifeline/enclosingObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="undirected" upperBound="-1" eType="//Tag__UndirectedPoint__Object_Lifeline" containment="true" eOpposite="//Tag__UndirectedPoint__Object_Lifeline/enclosingObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Object_Lifeline" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Lifeline" eOpposite="//Object__Object_Lifeline/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__InputPoint__Object_Lifeline" abstract="true" eSuperTypes="//InputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Lifeline" eOpposite="//Object__Object_Lifeline/input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__OutputPoint__Object_Lifeline" abstract="true" eSuperTypes="//OutputPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Lifeline" eOpposite="//Object__Object_Lifeline/output"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__UndirectedPoint__Object_Lifeline" abstract="true" eSuperTypes="//UndirectedPointGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingObject" ordered="false" lowerBound="1" eType="//Object__Object_Lifeline" eOpposite="//Object__Object_Lifeline/undirected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__Object_Lifeline" eSuperTypes="//InstanceRole //Tag__Object__Sequence_Diagram //Object__Object_Lifeline">
    <eAnnotations source="annotation">
      <details key="self" value="Object_Lifeline"/>
      <details key="parent" value="Sequence_Diagram"/>
      <details key="mode" value="propertyMode"/>
      <details key="shape" value="rectangle"/>
      <details key="metaInfo" value="生命线[Object_Lifeline]"/>
      <details key="properties" value=""/>
      <details key="input" value=""/>
      <details key="output" value=""/>
      <details key="undirected" value=""/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="生命线"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="highlight">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="decomposeN" eType="//Def__Sequence_Diagram__Object_Lifeline__decomposeN" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="explodesN" upperBound="-1" eType="//Def__Sequence_Diagram__Object_Lifeline__explodesN" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__Object_Lifeline__decomposeN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__Object_Lifeline__explodesN" eSuperTypes="//GraphGen"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Relationship_Event" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Event" eOpposite="//Relationship__Relationship_Event/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__Relationship_Event" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="事件"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Relationship_Event" containment="true" eOpposite="//Tag__Property__Relationship_Event/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__Relationship_Event" containment="true" eOpposite="//Tag__Role__Import__Relationship_Event/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__Relationship_Event" containment="true" eOpposite="//Tag__Role__Export__Relationship_Event/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__Relationship_Event" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Event" eOpposite="//Relationship__Relationship_Event/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__Relationship_Event" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Relationship_Event" eOpposite="//Relationship__Relationship_Event/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Relationship_Event_End" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Relationship_Event_End"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Relationship_Event__Relationship_Event_End" eSuperTypes="//Tag__Role__Import__Relationship_Event //Role__Relationship_Event_End //MessageEnd">
    <eAnnotations source="annotation">
      <details key="shape" value="arrowShape"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="事件终端 [ Relationship_Event_End ] "/>
      <details key="parent" value="Relationship_Event"/>
      <details key="LocalLabel" value="事件终端"/>
      <details key="self" value="Relationship_Event_End"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Relationship_Event_End" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="事件终端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Relationship_Event_End" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Relationship_Event_Start" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Relationship_Event_Start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Relationship_Event__Relationship_Event_Start" eSuperTypes="//Tag__Role__Export__Relationship_Event //Role__Relationship_Event_Start //MessageEnd">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="事件始端 [ Relationship_Event_Start ] "/>
      <details key="parent" value="Relationship_Event"/>
      <details key="LocalLabel" value="事件始端"/>
      <details key="self" value="Relationship_Event_Start"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Relationship_Event_Start" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="事件始端"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Relationship_Event_Start" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__Relationship_Event" eSuperTypes="//Tag__Relationship__Sequence_Diagram //Relationship__Relationship_Event //Message">
    <eAnnotations source="annotation">
      <details key="parent" value="Sequence_Diagram"/>
      <details key="self" value="Relationship_Event"/>
      <details key="roles" value="Relationship_Event_End,Relationship_Event_Start"/>
      <details key="LocalLabel" value="事件"/>
      <details key="metaInfo" value="事件 [ Relationship_Event ] "/>
      <details key="properties" value=""/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Message" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Message" eOpposite="//Relationship__Message/properties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship__Message" eSuperTypes="//RelationshipGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Message" containment="true" eOpposite="//Tag__Property__Message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRole" eType="//Tag__Role__Import__Message" containment="true" eOpposite="//Tag__Role__Import__Message/enclosingRelationship"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRole" eType="//Tag__Role__Export__Message" containment="true" eOpposite="//Tag__Role__Export__Message/enclosingRelationship"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Import__Message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Message" eOpposite="//Relationship__Message/fromRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Role__Export__Message" abstract="true" eSuperTypes="//RoleGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRelationship" ordered="false" lowerBound="1" eType="//Relationship__Message" eOpposite="//Relationship__Message/toRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_On_Port" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="处于端口"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Property_On_Port_3a7292" eSuperTypes="//Tag__Property__Message //Property__Property_On_Port">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="处于端口 [ Message_Property_On_Port_3a7292 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="处于端口"/>
      <details key="value" value="null"/>
      <details key="self" value="Message_Property_On_Port_3a7292"/>
      <details key="parent" value="Message"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="处于端口"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="处于端口"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Message_Sort" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息类"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Message_Sort_fa7423" eSuperTypes="//Tag__Property__Message //Property__Message_Sort">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="消息类 [ Message_Message_Sort_fa7423 ] "/>
      <details key="dataType" value="Enumeration"/>
      <details key="name" value="消息类"/>
      <details key="value" value="null"/>
      <details key="self" value="Message_Message_Sort_fa7423"/>
      <details key="parent" value="Message"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息类"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息类"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Property_To_Do_caf451" eSuperTypes="//Tag__Property__Message //Property__Property_To_Do">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="待办事项 [ Message_Property_To_Do_caf451 ] "/>
      <details key="dataType" value="String"/>
      <details key="name" value="待办事项"/>
      <details key="value" value="null"/>
      <details key="self" value="Message_Property_To_Do_caf451"/>
      <details key="parent" value="Message"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="待办事项"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="待办事项"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_Graph_Reference" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用图"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Property_Graph_Reference_dfd84f" eSuperTypes="//Tag__Property__Message //Property__Property_Graph_Reference">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="引用图 [ Message_Property_Graph_Reference_dfd84f ] "/>
      <details key="dataType" value="class&lt;Graph>"/>
      <details key="name" value="引用图"/>
      <details key="value" value="null"/>
      <details key="self" value="Message_Property_Graph_Reference_dfd84f"/>
      <details key="parent" value="Message"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用图"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用图"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_Object_Reference" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用对象"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Property_Object_Reference_803204" eSuperTypes="//Tag__Property__Message //Property__Property_Object_Reference">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="引用对象 [ Message_Property_Object_Reference_803204 ] "/>
      <details key="dataType" value="class&lt;Object>"/>
      <details key="name" value="引用对象"/>
      <details key="value" value="null"/>
      <details key="self" value="Message_Property_Object_Reference_803204"/>
      <details key="parent" value="Message"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用对象"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用对象"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property__Property_Point_Reference" eSuperTypes="//PropertyGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用点"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Property_Point_Reference_d95d63" eSuperTypes="//Tag__Property__Message //Property__Property_Point_Reference">
    <eAnnotations source="annotation">
      <details key="metaInfo" value="引用点 [ Message_Property_Point_Reference_d95d63 ] "/>
      <details key="dataType" value="class&lt;Point>"/>
      <details key="name" value="引用点"/>
      <details key="value" value="null"/>
      <details key="self" value="Message_Property_Point_Reference_d95d63"/>
      <details key="parent" value="Message"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用点"/>
    </eAnnotations>
    <eAnnotations source="LocalLabel">
      <details key="name" value="引用点"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Message_Source" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Message_Source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Source" eSuperTypes="//Tag__Role__Import__Message //Role__Message_Source">
    <eAnnotations source="annotation">
      <details key="shape" value="no"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="信息源 [ Message_Source ] "/>
      <details key="parent" value="Message"/>
      <details key="LocalLabel" value="信息源"/>
      <details key="self" value="Message_Source"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Message_Source" eSuperTypes="//ImportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="信息源"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Message_Source" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tag__Property__Message_Target" abstract="true" eSuperTypes="//PropertyGen">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enclosingRole" ordered="false" lowerBound="1" eType="//Role__Message_Target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Message__Message_Target" eSuperTypes="//Tag__Role__Export__Message //Role__Message_Target">
    <eAnnotations source="annotation">
      <details key="shape" value="arrowShape"/>
      <details key="properties" value=""/>
      <details key="metaInfo" value="消息目标 [ Message_Target ] "/>
      <details key="parent" value="Message"/>
      <details key="LocalLabel" value="消息目标"/>
      <details key="self" value="Message_Target"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role__Message_Target" eSuperTypes="//ExportRoleGen">
    <eAnnotations source="LocalLabel">
      <details key="name" value="消息目标"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1" eType="//Tag__Property__Message_Target" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Def__Sequence_Diagram__Message" eSuperTypes="//Tag__Relationship__Sequence_Diagram //Relationship__Message">
    <eAnnotations source="annotation">
      <details key="parent" value="Sequence_Diagram"/>
      <details key="self" value="Message"/>
      <details key="roles" value="Message_Source,Message_Target"/>
      <details key="LocalLabel" value="消息"/>
      <details key="metaInfo" value="消息 [ Message ] "/>
      <details key="properties" value="Def__Message__Message_Property_On_Port_3a7292,Message_Property_On_Port_3a7292,处于端口,null;Def__Message__Message_Message_Sort_fa7423,Message_Message_Sort_fa7423,消息类,null;Def__Message__Message_Property_To_Do_caf451,Message_Property_To_Do_caf451,待办事项,null;Def__Message__Message_Property_Graph_Reference_dfd84f,Message_Property_Graph_Reference_dfd84f,引用图,null;Def__Message__Message_Property_Object_Reference_803204,Message_Property_Object_Reference_803204,引用对象,null;Def__Message__Message_Property_Point_Reference_d95d63,Message_Property_Point_Reference_d95d63,引用点,null"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
